"""Compile the retained atlas into a deterministic, offline shared game dataset."""
import base64, csv, hashlib, json, struct, sys
from pathlib import Path
from PIL import Image

source = Path(sys.argv[1])
target = Path(__file__).resolve().parents[1] / 'shared/shire/atlasData.ts'
atlas = json.loads((source / 'shire-atlas.json').read_text(encoding='utf-8-sig'))
height = Image.open(source / 'height_u16.png')
encoded = base64.b64encode(struct.pack('<' + 'H' * (height.width * height.height), *height.getdata())).decode()
cover = base64.b64encode(Image.open(source / 'landcover_classes_u8.png').tobytes()).decode()
rivers = []
for river in atlas['rivers']:
    rows = list(csv.DictReader((source / river['sampled_centreline_and_stage_file']).open(encoding='utf-8-sig')))
    print(river['id'], len(rows), list(rows[0]))
    rivers.append(dict(id=river['id'], name=river['name'], width=sum(river['width_m'])/2,
        depth=sum(river['depth_m'])/2, points=[[round(float(r['east_km'])*1000,3), round(-float(r['north_km'])*1000,3), round(float(r['water_surface_design_m']),4)] for r in rows]))
places = [dict(id=p['id'],name=p['name'],kind=p['kind'],x=round(p['xy_km'][0]*1000,3),z=round(-p['xy_km'][1]*1000,3)) for p in atlas['places']]
roads = [dict(id=r['id'],name=r['name'],points=[[x*1000,-y*1000] for x,y in r['xy_km']]) for r in atlas['roads']]
payload = '// Generated by scripts/import-shire-atlas.py. All elevations and building layouts are designed.\n'
payload += 'export const ATLAS_SOURCE_SHA256 = '+json.dumps(hashlib.sha256((source/'shire-atlas.json').read_bytes()).hexdigest())+'\n'
payload += 'export const HEIGHT_BASE64:string = '+json.dumps(encoded)+'\nexport const COVER_BASE64:string = '+json.dumps(cover)+'\n'
payload += 'export const ATLAS_PLACES: {id:string;name:string;kind:string;x:number;z:number}[] = '+json.dumps(places,separators=(',',':'))+'\n'
payload += 'export const ATLAS_RIVERS: {id:string;name:string;width:number;depth:number;points:number[][]}[] = '+json.dumps(rivers,separators=(',',':'))+'\n'
payload += 'export const ATLAS_ROADS: {id:string;name:string;points:number[][]}[] = '+json.dumps(roads,separators=(',',':'))+'\n'
target.write_text(payload,encoding='utf-8')
print(target, target.stat().st_size)
