import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import {createWorld,advanceWorld,applyAction,validateWorld} from '../shared/shire/simulation'
import {ensureLife} from '../shared/shire/life'
import {combatActor,resetPlayerTracking,safeCombatGround,damage,playerRespawn,playerStrike} from '../shared/shire/combat'
import {height,clear} from '../shared/shire/terrain'
import {populateRegion} from '../shared/shire/lifeSpatial'
import {places} from '../shared/shire/lifeContent'
import type {World} from '../shared/shire/model'

const results:Array<{name:string;ms:number}>=[]
function check(name:string,fn:()=>void){const start=performance.now();fn();results.push({name,ms:performance.now()-start});console.log('PASS '+name)}
function encounter(species:string,range:number){const w=createWorld('Behaviour review',42,'shire-1');w.time=200;ensureLife(w,'creative');const a=combatActor(w,'hostile:'+species)!;const p=safeCombatGround(w,{x:-150,y:0,z:-300});a.position={...p};a.home={...p};a.phase='idle';a.targetId=undefined;w.player={...p,z:p.z+range,yaw:0,pitch:0};w.player.y=height(w.player.x,w.player.z,w)+.08;resetPlayerTracking(w);for(const b of w.combat!.actors)if(b.id!=='player'&&b.id!==a.id)b.position={...b.position,x:1400,z:-1400};return{w,a}}
check('spider waits beyond ambush distance, then pursues when approached',()=>{const {w,a}=encounter('07-great-spider',11),start={...a.position};advanceWorld(w,1);assert.equal(a.targetId,undefined);assert(Math.hypot(a.position.x-start.x,a.position.z-start.z)<.1);w.player.z=a.position.z+5;resetPlayerTracking(w);advanceWorld(w,.8);assert.equal(a.targetId,'player');assert(a.position.z>start.z+.5)})
check('sling shot can be dodged after release and hits a stationary target',()=>{const {w,a}=encounter('21-rhudaur-hillman',12);advanceWorld(w,1.5);assert(w.combat!.projectiles?.length);const hp=combatActor(w,'player')!.vitality.hp;w.player.x+=4;resetPlayerTracking(w);advanceWorld(w,1);assert.equal(combatActor(w,'player')!.vitality.hp,hp);w.player.x=a.position.x;resetPlayerTracking(w);advanceWorld(w,4);assert(combatActor(w,'player')!.vitality.hp<hp)})
check('warg moves sideways to flank and withdraws during recovery',()=>{const {w,a}=encounter('08-warg',7),x=a.position.x;advanceWorld(w,.7);assert(Math.abs(a.position.x-x)>.25);a.phase='recover';a.vitality.cooldownUntil=w.time+2;a.targetId='player';const before=Math.hypot(a.position.x-w.player.x,a.position.z-w.player.z);advanceWorld(w,.5);assert(Math.hypot(a.position.x-w.player.x,a.position.z-w.player.z)>before)})
check('enforcer guards after a strike and wight drains stamina',()=>{const {w,a}=encounter('03-half-orc',2);advanceWorld(w,1);assert(a.vitality.blockingUntil>w.time);const hp=a.vitality.hp,dealt=damage(w,a,40,'physical','player');assert(dealt<15&&a.vitality.hp<hp);const other=encounter('23-barrow-wight',2);advanceWorld(other.w,1);assert(combatActor(other.w,'player')!.vitality.stamina<90)})
check('bow spends an arrow, flies before impact, and resolves authoritative damage',()=>{const {w,a}=encounter('01-orc',20);w.life!.equipment.weapon='bow';w.life!.inventory.arrow=4;const hp=a.vitality.hp;playerStrike(w,a.id);assert.equal(w.life!.inventory.arrow,3);assert.equal(a.vitality.hp,hp);assert.equal(w.combat!.projectiles!.length,1);advanceWorld(w,.8);assert(a.vitality.hp<hp)})
check('return home and defeat recovery safely leave pocket interiors',()=>{const {w}=encounter('01-orc',20);const p=places(w).find(p=>p.kind==='inn')!;w.player={...p.door,y:height(p.door.x,p.door.z,w)+.08,yaw:0,pitch:0};resetPlayerTracking(w);applyAction(w,{type:'life',action:{kind:'enter',id:p.id}});applyAction(w,{type:'return-home'});assert(!w.life!.interior);assert(clear(w.player,w));w.player={...p.door,y:height(p.door.x,p.door.z,w)+.08,yaw:0,pitch:0};resetPlayerTracking(w);applyAction(w,{type:'life',action:{kind:'enter',id:p.id}});damage(w,combatActor(w,'player')!,10000,'fall');advanceWorld(w,3.1);playerRespawn(w);assert(!w.life!.interior);assert(clear(w.player,w));validateWorld(w)})
check('regional population includes fish and bank life and never duplicates on revisit',()=>{const w=createWorld('Habitats',42,'shire-atlas-1');ensureLife(w,'homestead');populateRegion(w);assert(w.animals.some(a=>a.species==='fish'),'Hobbiton needs fish');assert(w.animals.some(a=>a.species==='frog'),'Hobbiton needs frogs');const ids=w.animals.map(a=>a.id);populateRegion(w);assert.deepEqual(w.animals.map(a=>a.id),ids);validateWorld(w)})
void fs.writeFile('E:/GrudgeBloxData/TheMiddleEarth/evidence/immersive-2026-09-10/behaviour-source-checks.json',JSON.stringify({at:new Date().toISOString(),evidenceCategory:'source integration; browser combat and motion remain separate',results},null,2)).catch(e=>{console.error(e);process.exitCode=1})
