import { test } from 'node:test'
import assert from 'node:assert/strict'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import { createWorld, applyAction, advanceWorld, validateWorld } from '../shared/shire/simulation'
import { ensureCombat, combatActor, damage, heal, playerStrike, playerGuard, playerHeal, playerRespawn, attackClear, observePlayer, resetPlayerTracking, safeCombatGround, encounterTravel } from '../shared/shire/combat'
import { HOSTILES } from '../shared/shire/hostiles'
import { LocalWorldStore } from '../back/src/shire/LocalWorldStore'
import type { World } from '../shared/shire/model'
const fresh=()=>createWorld('Combat verification',42)
const player=(w:World)=>combatActor(w,'player')!
const orc=(w:World)=>combatActor(w,'hostile:01-orc')!
function encounter(){const w=fresh(),a=orc(w);w.time=10;w.player={...safeCombatGround(w,a.home),x:a.home.x,y:a.home.y,z:a.home.z+2,yaw:0,pitch:0};resetPlayerTracking(w);a.position={...a.home};return w}

test('all 25 representatives, Cinderlord, residents and wildlife have unique health records in both worlds',()=>{for(const generator of ['shire-1','shire-atlas-1'] as const){const w=createWorld('Roster',42,generator);validateWorld(w);assert.equal(w.combat!.actors.filter(a=>a.kind==='hostile').length,26);for(const d of HOSTILES)assert.equal(combatActor(w,`hostile:${d.id}`)!.vitality.maxHp,d.hp);for(const a of w.animals)assert.ok(combatActor(w,a.id));assert.ok(w.combat!.actors.some(a=>a.kind==='resident'));advanceWorld(w,.8);validateWorld(w)}})
test('legacy saves migrate additively and migration is idempotent',()=>{const w=fresh();delete w.combat;const animals=JSON.stringify(w.animals);validateWorld(w);ensureCombat(w);const count=w.combat!.actors.length;ensureCombat(w);assert.equal(w.combat!.actors.length,count);assert.equal(JSON.stringify(w.animals),animals);validateWorld(w)})
test('strikes validate targets, reach, stamina and cooldown; client damage amounts are ignored',()=>{const w=encounter(),a=orc(w);assert.throws(()=>playerStrike(w,'missing'));assert.throws(()=>playerStrike(w,'player'));const before=a.vitality.hp;applyAction(w,{type:'strike',id:a.id,amount:999999} as never);assert.ok(a.vitality.hp<before&&a.vitality.hp>0);assert.throws(()=>playerStrike(w,a.id),/ready/);w.time+=1;player(w).vitality.stamina=0;assert.throws(()=>playerStrike(w,a.id),/breath/);player(w).vitality.stamina=100;w.player.x+=100;assert.throws(()=>playerStrike(w,a.id),/closer/);validateWorld(w)})
test('all actor kinds use the same bounded damage and healing rules',()=>{const w=fresh();w.time=1;for(const kind of ['player','resident','animal','hostile']){const a=w.combat!.actors.find(b=>b.kind===kind)!;const before=a.vitality.hp;assert.ok(damage(w,a,8,'physical')>0);assert.ok(a.vitality.hp<before);heal(w,a,9999);assert.equal(a.vitality.hp,a.vitality.maxHp);assert.equal(damage(w,a,NaN,'fire'),0);assert.equal(damage(w,a,-8,'fire'),0)}validateWorld(w)})
test('armour, elemental immunity and weakness alter damage',()=>{const w=fresh();w.time=1;const a=orc(w),b=combatActor(w,'hostile:11-balrog')!,c=combatActor(w,'hostile:22-nazgul')!;a.vitality.armour=100;assert.equal(damage(w,a,20,'physical'),10);assert.equal(damage(w,b,20,'fire'),0);assert.equal(damage(w,c,20,'poison'),0);assert.equal(damage(w,c,20,'fire','environment',false),28)})
test('guard requires facing, consumes stamina and reduces incoming damage',()=>{const w=encounter(),p=player(w),a=orc(w);playerGuard(w);const blocked=damage(w,p,20,'physical',a.id,false);assert.ok(blocked<10);assert.equal(p.vitality.stamina,88);p.yaw=Math.PI;const rear=damage(w,p,20,'physical',a.id,false);assert.ok(rear>blocked);assert.equal(p.vitality.stamina,88)})
test('burn and poison tick, expire and are removed by healing draughts',()=>{const w=fresh();w.time=10;const p=player(w);damage(w,p,5,'fire');damage(w,p,5,'poison');assert.equal(p.vitality.effects.length,2);const hp=p.vitality.hp;advanceWorld(w,1.2);assert.ok(p.vitality.hp<hp);playerHeal(w);assert.equal(p.vitality.effects.length,0);assert.equal(w.combat!.healingDraughts,2);damage(w,p,5,'poison');advanceWorld(w,6);assert.equal(p.vitality.effects.length,0);validateWorld(w)})
test('death is emitted once and blocks attacks, care, breeding, healing and movement observations',()=>{const w=encounter(),p=player(w),a=w.animals[0];damage(w,combatActor(w,a.id)!,999,'physical');assert.throws(()=>applyAction(w,{type:'feed',id:a.id}),/defeated/);const oldHP=combatActor(w,a.id)!.vitality.hp;heal(w,combatActor(w,a.id)!,50);assert.equal(oldHP,0);damage(w,p,999,'physical');const deaths=w.combat!.events.filter(e=>e.type==='death'&&e.target==='player').length;damage(w,p,10,'fire');assert.equal(w.combat!.events.filter(e=>e.type==='death'&&e.target==='player').length,deaths);assert.throws(()=>playerStrike(w,orc(w).id),/defeated/);assert.throws(()=>applyAction(w,{type:'travel',settlement:0}),/defeated/);const before={...w.player};observePlayer(w,{...w.player,x:999});assert.deepEqual(w.player,before);validateWorld(w)})
test('player recovery restores health at home and temporary protection prevents immediate damage',()=>{const w=fresh();w.time=10;damage(w,player(w),999,'physical');assert.throws(()=>playerRespawn(w),/three seconds/);advanceWorld(w,3.1);playerRespawn(w);assert.equal(player(w).vitality.hp,100);assert.equal(damage(w,player(w),50,'physical'),0);assert.equal(player(w).phase,'idle');assert.equal(player(w).generation,1);validateWorld(w)})
test('defeated enemies respawn once on their own timer',()=>{const w=fresh();w.time=10;const a=orc(w);damage(w,a,999,'physical');advanceWorld(w,119);assert.equal(a.vitality.hp,0);advanceWorld(w,2);assert.equal(a.vitality.hp,a.vitality.maxHp);assert.equal(a.generation,1);advanceWorld(w,1);assert.equal(a.generation,1);validateWorld(w)})
test('enemy windup applies one impact and attacks stop after death',()=>{const w=encounter(),a=orc(w),p=player(w);advanceWorld(w,.2);assert.equal(a.phase,'windup');assert.equal(p.vitality.hp,100);advanceWorld(w,.9);assert.ok(p.vitality.hp<100);assert.equal(w.combat!.events.filter(e=>e.type==='damage'&&e.source===a.id).length,1);damage(w,a,999,'physical');const hp=p.vitality.hp;advanceWorld(w,3);assert.equal(p.vitality.hp,hp);validateWorld(w)})
test('closed doors obstruct both player and enemy attacks',()=>{const w=encounter(),a=orc(w),p=player(w);assert.equal(attackClear(w,p,a),true);w.furniture.push({id:crypto.randomUUID(),kind:'door',position:{x:a.position.x,y:a.position.y,z:a.position.z+1},yaw:0,open:false});assert.equal(attackClear(w,p,a),false);assert.throws(()=>playerStrike(w,a.id),/clear line/);w.furniture[0].open=true;assert.equal(attackClear(w,p,a),true)})
test('residents retaliate using the same damage service',()=>{const w=fresh();w.time=10;const r=w.combat!.actors.find(a=>a.kind==='resident')!;w.player={...r.position,z:r.position.z+2,yaw:0,pitch:0};resetPlayerTracking(w);playerStrike(w,r.id);assert.equal(r.targetId,'player');advanceWorld(w,1.2);assert.ok(player(w).vitality.hp<100)})
test('fall impact and depleted underwater breath cause health damage',()=>{const w=fresh();w.time=10;const p={...w.player};observePlayer(w,{...p,y:p.y+8});assert.equal(w.combat!.grounded,false);observePlayer(w,p);assert.ok(player(w).vitality.hp<100);const water={x:25,y:0,z:114,yaw:0,pitch:0};w.player=water;resetPlayerTracking(w);const before=player(w).vitality.hp;player(w).vitality.breath=0;advanceWorld(w,1.1);assert.ok(player(w).vitality.hp<before)})
test('malformed health, duplicate identity, effects, event history and NaN time are rejected',()=>{for(const mutate of [(w:World)=>{player(w).vitality.hp=NaN},(w:World)=>{w.combat!.actors.push(player(w))},(w:World)=>{player(w).vitality.hp=101},(w:World)=>{player(w).phase='dead'},(w:World)=>{player(w).vitality.effects=[{kind:'burn',source:'environment',remaining:Infinity,nextTick:1,damage:2}] }]){const w=fresh();mutate(w);assert.throws(()=>validateWorld(w))}assert.throws(()=>advanceWorld(fresh(),NaN))})
test('combat state persists across store restart; rejected actions do not alter durable state',async()=>{const root=await fs.mkdtemp('E:/GrudgeBloxData/TheMiddleEarth/evidence/hostile-combat-20260908/store-'),store=new LocalWorldStore(root),w=encounter();damage(w,orc(w),12,'physical');damage(w,player(w),7,'poison');const imported=await store.import(w);const reopened=await new LocalWorldStore(root).read(imported.id);assert.equal(player(reopened).vitality.hp,player(imported).vitality.hp);assert.equal(orc(reopened).vitality.hp,orc(imported).vitality.hp);assert.equal(player(reopened).vitality.effects[0].kind,'poison');await assert.rejects(store.act(imported.id,imported.revision,{type:'strike',id:'missing'}));const head=JSON.parse(await fs.readFile(path.join(root,'saves',imported.id,'current.json'),'utf8'));const after=JSON.parse(await fs.readFile(path.join(root,'saves',imported.id,head.file),'utf8'));assert.deepEqual(after.combat,imported.combat);await fs.writeFile(path.join(root,'TEST_PASSED.txt'),'Combat persistence and rejection preservation verified.')})

test('every encounter approach is clear and outside detection in both world generators',()=>{for(const generator of ['shire-1','shire-atlas-1'] as const){const w=createWorld('Approaches',42,generator);for(const d of HOSTILES){encounterTravel(w,`hostile:${d.id}`);const a=combatActor(w,`hostile:${d.id}`)!;assert.ok(Math.hypot(w.player.x-a.home.x,w.player.z-a.home.z)>d.aggro);observePlayer(w,w.player);validateWorld(w)}}})

test('swimming absorbs a fall and resets the landing height',()=>{const w=fresh();w.time=10;w.player={x:25,y:2.5-1.15,z:114,yaw:0,pitch:0};w.combat!.peakY=40;observePlayer(w,w.player);assert.equal(w.combat!.peakY,w.player.y);assert.equal(player(w).vitality.hp,100)})
