import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import { createHash } from 'node:crypto'
import { createWorld,applyAction,advanceWorld,validateWorld } from '../shared/shire/simulation'
import { breedingIssue } from '../shared/shire/animalCare'
import { clear,density,height,meshChunk,hasOutdoorExit } from '../shared/shire/terrain'
import { SPECIES,Species,id } from '../shared/shire/model'
import { LocalWorldStore } from '../back/src/shire/LocalWorldStore'
import { expansionChecks } from './shire-expansion-checks'

async function main(){
const checks:Array<{name:string;milliseconds:number}>=[]
const check=async(name:string,fn:()=>unknown|Promise<unknown>)=>{const start=performance.now();await fn();checks.push({name,milliseconds:Math.round(performance.now()-start)});console.log(`PASS ${name}`)}
const root=path.join('E:\\GrudgeBloxData\\TheMiddleEarth\\evidence',`storage-check-${Date.now()}`)
await fs.mkdir(root,{recursive:true})
await check('new world has ten adult pairs and a valid supported spawn',()=>{const w=createWorld();validateWorld(w);assert.equal(w.animals.length,20);assert.ok(clear(w.player,w));for(const s of Object.keys(SPECIES))assert.equal(w.animals.filter(a=>a.species===s).length,2)})
const cave=createWorld(),roof=height(-30,-6,cave.seed),floor=roof-5
cave.player={x:-30,y:roof+0.1,z:-6,yaw:0,pitch:0}
await check('excavation leaves a genuine floor, hollow room and solid roof',()=>{applyAction(cave,{type:'excavate',edit:{kind:'dig',shape:'box',center:{x:-30,y:floor+1.5,z:-6},size:{x:6,y:3,z:6},yaw:0,entrance:false}});assert.ok(density(-30,floor+1.5,-6,cave.seed,cave.edits)<0);assert.ok(density(-30,floor-0.2,-6,cave.seed,cave.edits)>0);assert.ok(density(-30,floor+3.3,-6,cave.seed,cave.edits)>0);assert.ok(clear({x:-30,y:floor+0.1,z:-6},cave))})
await check('a wide room cannot break through the downslope edge of its roof',()=>{const w=createWorld();w.player={x:-41.5,y:height(-41.5,-17.5)+0.1,z:-17.5,yaw:0,pitch:0};assert.throws(()=>applyAction(w,{type:'excavate',edit:{kind:'dig',shape:'box',center:{x:-41.5,y:11.536622110096113,z:-17.5},size:{x:6,y:2.5,z:6},yaw:0,entrance:false}}),/above part of this room/);assert.equal(w.edits.length,0)})
await check('undo refuses to bury a player inside the room',()=>{applyAction(cave,{type:'checkpoint',player:{x:-30,y:floor+0.1,z:-6,yaw:0,pitch:0}});assert.throws(()=>applyAction(cave,{type:'undo'}),/Step outside/);assert.equal(cave.edits.length,1)})
await check('floor collision agrees with the cut volume and cannot tunnel through its wall',()=>{assert.ok(!clear({x:-26.8,y:floor+0.1,z:-6},cave));assert.ok(!clear({x:-30,y:floor-0.25,z:-6},cave));assert.ok(!hasOutdoorExit(cave.player,cave))})
await check('edited meshing creates downward ceiling and upward floor faces with finite vertices',()=>{const mesh=meshChunk(-2,-1,cave.seed,cave.edits,0.5);assert.ok(mesh.positions.length>0);assert.ok([...mesh.positions,...mesh.normals].every(Number.isFinite));let up=0,down=0;for(let i=0;i<mesh.normals.length;i+=3){if(mesh.normals[i+1]>.8)up++;if(mesh.normals[i+1]<-.8)down++}assert.ok(up>0&&down>0)})
await check('furniture placement, collision, removal and household storage act on durable state',()=>{applyAction(cave,{type:'furnish',kind:'chest',position:{x:-28.3,y:floor+0.04,z:-5},yaw:0});assert.ok(!clear({x:-28.3,y:floor+0.1,z:-5},cave));cave.supplies.barley=6;applyAction(cave,{type:'store'});assert.equal(cave.storage.barley,6);assert.equal(cave.supplies.barley,0);applyAction(cave,{type:'withdraw'});assert.equal(cave.supplies.barley,6);applyAction(cave,{type:'remove-furniture',id:cave.furniture[0].id});assert.equal(cave.furniture.length,0)})
await check('home recovery resolves clear ground when furniture occupies the marker',()=>{const w=createWorld(),p={x:-60,y:height(-60,22)+.03,z:22};applyAction(w,{type:'claim',position:p});applyAction(w,{type:'furnish',kind:'chest',position:p,yaw:0});applyAction(w,{type:'return-home'});assert.ok(clear(w.player,w));assert.ok(Math.hypot(w.player.x-p.x,w.player.z-p.z)>0.7);applyAction(w,{type:'checkpoint',player:w.player});applyAction(w,{type:'remove-furniture',id:w.furniture[0].id});validateWorld(w)})
await check('home recovery avoids a deep shaft and returns to supported outdoor ground',()=>{const w=createWorld();w.home={x:-60,y:height(-60,22),z:22};w.edits=[8,3,-2,-7,-12,-17,-22,-27,-30,-34].map(y=>({id:id(),kind:'dig',shape:'sphere',center:{x:-60,y,z:22},size:{x:3,y:3,z:3},yaw:0,entrance:true}));applyAction(w,{type:'return-home'});assert.ok(w.player.y>0);assert.ok(clear(w.player,w));assert.ok(density(w.player.x,w.player.y-0.4,w.player.z,w.seed,w.edits)>0);applyAction(w,{type:'checkpoint',player:w.player});validateWorld(w)})
await check('planting, watering, timed growth and a single harvest return usable supplies',()=>{const w=createWorld(),p={x:-63,y:height(-63,22,w.seed)+.03,z:22};w.player={...p,yaw:0,pitch:0};applyAction(w,{type:'plant',kind:'barley',position:p});const cid=w.crops[0].id;assert.throws(()=>applyAction(w,{type:'harvest',id:cid}),/not ripe/);applyAction(w,{type:'water',id:cid});advanceWorld(w,59);assert.throws(()=>applyAction(w,{type:'harvest',id:cid}),/not ripe/);advanceWorld(w,1);applyAction(w,{type:'harvest',id:cid});assert.equal(w.supplies.barley,3);assert.equal(w.supplies.barleySeed,41);assert.equal(w.supplies.feed,84);assert.throws(()=>applyAction(w,{type:'harvest',id:cid}),/already/);validateWorld(w)})
await check('every species produces one young animal with valid two-parent lineage',()=>{for(const species of Object.keys(SPECIES) as Species[]){const w=createWorld(),[dam,sire]=w.animals.filter(a=>a.species===species);w.player={...dam.position,yaw:0,pitch:0};applyAction(w,{type:'breed',dam:dam.id,sire:sire.id});assert.throws(()=>applyAction(w,{type:'breed',dam:dam.id,sire:sire.id}),/need time/);let remaining=SPECIES[species].gestation;while(remaining>0){const dt=Math.min(remaining,120);advanceWorld(w,dt);remaining-=dt}assert.equal(w.animals.length,21);const young=w.animals[20];assert.deepEqual(young.parents,[dam.id,sire.id]);assert.equal(young.species,species);validateWorld(w)}})
await check('young, hungry and mismatched animals cannot breed',()=>{const w=createWorld(),dam=w.animals[0],sire=w.animals[1];w.player={...dam.position,yaw:0,pitch:0};dam.age=0;assert.throws(()=>applyAction(w,{type:'breed',dam:dam.id,sire:sire.id}),/grow into adults/);dam.age=1000;w.time=200;assert.throws(()=>applyAction(w,{type:'breed',dam:dam.id,sire:sire.id}),/Feed both/);dam.fedUntil=sire.fedUntil=300;assert.throws(()=>applyAction(w,{type:'breed',dam:dam.id,sire:w.animals[3].id}),/same species/);})
await check('care-panel eligibility agrees with authoritative breeding after feeding and recovery',()=>{const w=createWorld(),dam=w.animals[0],sire=w.animals[1];w.player={...dam.position,yaw:0,pitch:0};w.time=200;assert.match(breedingIssue(w,dam.id,sire.id)||'',/Feed both/);applyAction(w,{type:'feed',id:dam.id});applyAction(w,{type:'feed',id:sire.id});assert.equal(breedingIssue(w,dam.id,sire.id),null);applyAction(w,{type:'breed',dam:dam.id,sire:sire.id});assert.match(breedingIssue(w,dam.id,sire.id)||'',/young are due/);advanceWorld(w,90);assert.match(breedingIssue(w,dam.id,sire.id)||'',/recover/);assert.match(breedingIssue(w,dam.id,sire.id,{x:1000,y:0,z:1000})||'',/closer/);})
await check('harvested plots no longer consume the 500 active crop budget',()=>{const w=createWorld();w.crops=Array.from({length:500},()=>({id:id(),kind:'barley',position:{x:-60,y:height(-60,22),z:22},planted:0,watered:true,harvested:true}));applyAction(w,{type:'plant',kind:'carrot',position:{x:-60,y:height(-60,22)+.03,z:22}});assert.equal(w.crops.length,1);assert.equal(w.crops[0].kind,'carrot')})
await check('pending offspring reserve the last population slot',()=>{const w=createWorld();while(w.animals.length<99)w.animals.push({...structuredClone(w.animals[0]),id:id()});w.player={...w.animals[0].position,yaw:0,pitch:0};applyAction(w,{type:'breed',dam:w.animals[0].id,sire:w.animals[1].id});w.player={...w.animals[2].position,yaw:0,pitch:0};assert.throws(()=>applyAction(w,{type:'breed',dam:w.animals[2].id,sire:w.animals[3].id}),/population is full/);advanceWorld(w,90);assert.equal(w.animals.length,100);assert.ok(w.animals[99].parents)})
await check('invalid imports fail closed for missing supplies, duplicate identity, NaN and broken lineage',()=>{const broken=createWorld();delete (broken.supplies as Partial<typeof broken.supplies>).feed;assert.throws(()=>validateWorld(broken),/supplies/);const duplicate=createWorld();duplicate.animals[1].id=duplicate.animals[0].id;assert.throws(()=>validateWorld(duplicate),/duplicate/);const nan=createWorld();nan.player.y=NaN;assert.throws(()=>validateWorld(nan),/header/);const lineage=createWorld();lineage.animals[0].parents=[id(),id()];assert.throws(()=>validateWorld(lineage),/lineage/)})
await check('local world revisions survive a fresh store and reject stale actions',async()=>{const store=new LocalWorldStore(root),w=await store.create('Storage verification',42);const result=await store.act(w.id,w.revision,{type:'save'});const reopened=await new LocalWorldStore(root).read(w.id);assert.equal(reopened.revision,result.world.revision);assert.equal(reopened.id,w.id);await assert.rejects(store.act(w.id,0,{type:'save'}),/world changed/);})
await check('full edited world export and import preserve terrain, crop, animals, pose and lineage',async()=>{const store=new LocalWorldStore(root),imported=await store.import(cave),backup=await store.export(imported.id);assert.ok(backup.backupPath.startsWith(root+path.sep));const disk=JSON.parse(await fs.readFile(backup.backupPath,'utf8'));const restored=await store.import(disk);assert.notEqual(restored.id,imported.id);assert.deepEqual(restored.edits,cave.edits);assert.deepEqual(restored.player,cave.player);assert.deepEqual(restored.animals,cave.animals);})
await check('offspring keep distinct names and their actual parents through save and reopen',async()=>{const w=createWorld(),dam=w.animals[0],sire=w.animals[1];w.player={...dam.position,yaw:0,pitch:0};applyAction(w,{type:'breed',dam:dam.id,sire:sire.id});advanceWorld(w,90);const first=w.animals.at(-1)!;advanceWorld(w,120);w.player={...dam.position,yaw:0,pitch:0};applyAction(w,{type:'feed',id:dam.id});w.player={...sire.position,yaw:0,pitch:0};applyAction(w,{type:'feed',id:sire.id});w.player={x:(dam.position.x+sire.position.x)/2,y:(dam.position.y+sire.position.y)/2,z:(dam.position.z+sire.position.z)/2,yaw:0,pitch:0};applyAction(w,{type:'breed',dam:dam.id,sire:sire.id});advanceWorld(w,90);const second=w.animals.at(-1)!;assert.notEqual(first.name,second.name);const store=new LocalWorldStore(root),saved=await store.import(w),reopened=await new LocalWorldStore(root).read(saved.id);for(const young of [first,second]){const retained=reopened.animals.find(a=>a.id===young.id)!;assert.equal(retained.name,young.name);assert.deepEqual(retained.parents,[dam.id,sire.id]);assert.equal(reopened.animals.find(a=>a.id===retained.parents![0])?.name,dam.name);assert.equal(reopened.animals.find(a=>a.id===retained.parents![1])?.name,sire.name)}})
await check('corrupt current save is visible and recovery clones the previous revision without overwriting original',async()=>{const store=new LocalWorldStore(root),w=await store.create('Recovery verification',42);await store.act(w.id,0,{type:'save'});const dir=path.join(root,'saves',w.id),head=JSON.parse(await fs.readFile(path.join(dir,'current.json'),'utf8')),file=path.join(dir,head.file);await fs.writeFile(file,'corrupt current revision');const before=createHash('sha256').update(await fs.readFile(file)).digest('hex'),fresh=new LocalWorldStore(root);await assert.rejects(fresh.read(w.id),/checksum/);assert.equal((await fresh.list()).find(s=>s.id===w.id)?.revision,-1);const recovered=await fresh.recover(w.id);assert.notEqual(recovered.id,w.id);assert.equal(recovered.revision,0);assert.equal(createHash('sha256').update(await fs.readFile(file)).digest('hex'),before)})
await check('revision retention preserves both recoverable heads after repeated atomic replacements',async()=>{const store=new LocalWorldStore(root);let w=await store.create('Retention verification',42);for(let i=0;i<15;i++)w=(await store.act(w.id,w.revision,{type:'save'})).world;const dir=path.join(root,'saves',w.id),files=await fs.readdir(dir);assert.ok(files.filter(f=>f.startsWith('revision-')).length<=12);for(const name of ['current.json','previous.json']){const head=JSON.parse(await fs.readFile(path.join(dir,name),'utf8'));await fs.access(path.join(dir,head.file))}assert.equal((await new LocalWorldStore(root).recover(w.id)).revision,0)})
await check('long-named worlds can be recovered repeatedly',async()=>{const store=new LocalWorldStore(root);let w=await store.create('A'.repeat(60),42);for(let i=0;i<3;i++){w=(await store.act(w.id,w.revision,{type:'save'})).world;w=await store.recover(w.id);assert.ok(w.name.length<=60);validateWorld(w)}})
await expansionChecks(check,root)
const report={createdAt:new Date().toISOString(),scope:'Source and filesystem checks only. These do not establish running-game or visual acceptance.',status:'pass',checks,storage:root}
await fs.writeFile(path.join(root,'report.json'),JSON.stringify(report,null,2))
await fs.writeFile('E:\\GrudgeBloxData\\TheMiddleEarth\\evidence\\source-checks-latest.json',JSON.stringify(report,null,2))
console.log(JSON.stringify({passed:checks.length,report:path.join(root,'report.json')}))
}
main().catch(error=>{console.error(error);process.exitCode=1})
