import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import { createWorld, applyAction, advanceWorld, validateWorld } from '../shared/shire/simulation'
import { ensureLife, itemCount, questProgress, validateLife } from '../shared/shire/life'
import { placeById, places, QUESTS, residentDetails, dayAt } from '../shared/shire/lifeContent'
import { suggestedHome, resourceNodes, ferryCrossing, storyPlaces } from '../shared/shire/lifeSpatial'
import { clear, height } from '../shared/shire/terrain'
import { combatActor, observePlayer, resetPlayerTracking, safeCombatGround, actorEnabled } from '../shared/shire/combat'
import { LocalWorldStore } from '../back/src/shire/LocalWorldStore'
import { observation, mergeObservation } from '../shared/shire/observation'
import { ATLAS_DESTINATIONS } from '../shared/shire/atlas'
import type { World, WorldAction, Point } from '../shared/shire/model'

const evidence='E:/GrudgeBloxData/TheMiddleEarth/evidence/immersive-2026-09-10'
let w=createWorld('Village life checks',918,'shire-atlas-1');w.time=200;ensureLife(w,'homestead')
const results:Array<{name:string;ms:number}>=[]
async function check(name:string,fn:()=>unknown|Promise<unknown>){const start=performance.now();await fn();results.push({name,ms:Math.round(performance.now()-start)});console.log('PASS '+name)}
function act(a:WorldAction){const copy=structuredClone(w),message=applyAction(copy,a);validateWorld(copy);w=copy;return message}
function position(p:Point){const copy=structuredClone(w);copy.player={...copy.player,...p};resetPlayerTracking(copy);assert(clear(copy.player,copy),'Fixture position must be clear');w=copy}
function enterInn(town='hobbiton'){if(w.life!.interior)act({type:'life',action:{kind:'exit'}});const inn=places(w).find(p=>p.town===town&&p.kind==='inn')!;position({...inn.door,y:height(inn.door.x,inn.door.z,w)+.08});act({type:'life',action:{kind:'enter',id:inn.id}});return inn}

async function main(){
await check('new life state validates with 215 named residents and retained identities',()=>{validateWorld(w);assert.equal(w.life!.residents.length,215);assert.equal(new Set(w.life!.residents.map(r=>r.id)).size,215);assert(w.life!.residents.every(r=>r.name!==combatActor(w,r.id)?.id));assert.equal(w.animals.length,14)})
await check('Homestead excludes every hostile from gameplay collision and combat',()=>{assert(w.combat!.actors.filter(a=>a.kind==='hostile').every(a=>!actorEnabled(w,a)));assert.throws(()=>act({type:'strike',id:'hostile:01-orc'}),/disabled|Homestead/);const hp=combatActor(w,'player')!.vitality.hp;advanceWorld(w,2);assert.equal(combatActor(w,'player')!.vitality.hp,hp)})
await check('public inn entry, room floor, host conversation and welcome reward work together',()=>{const inn=enterInn();assert.equal(w.life!.interior!.id,inn.id);assert(clear(w.player,w));const hp=combatActor(w,'player')!.vitality.hp;advanceWorld(w,10);assert.equal(combatActor(w,'player')!.vitality.hp,hp);act({type:'life',action:{kind:'talk',id:w.life!.interior!.keeper!}});assert.equal(w.life!.quests.welcome.state,'ready');const coins=w.life!.coins;act({type:'life',action:{kind:'quest-complete',id:'welcome'}});assert.equal(w.life!.coins,coins+25);assert.throws(()=>act({type:'life',action:{kind:'quest-complete',id:'welcome'}}),/already/);act({type:'life',action:{kind:'exit'}});assert(clear(w.player,w))})
await check('shared workshop hosts can each be visited indoors',()=>{const v=structuredClone(w),barn=places(v).find(p=>p.town==='hobbiton'&&p.kind==='barn')!;v.player={...v.player,...barn.door,y:height(barn.door.x,barn.door.z,v)+.08};resetPlayerTracking(v);applyAction(v,{type:'life',action:{kind:'enter',id:barn.id}});for(const role of ['farmer','carpenter']){const resident=v.life!.residents.find(r=>r.town==='hobbiton'&&r.role===role)!;assert.equal(resident.workBuilding,barn.id);applyAction(v,{type:'life',action:{kind:'talk',id:resident.id}});assert.equal(v.life!.interior!.keeper,resident.id)}validateWorld(v)})
await check('garden plans reject unsupported soil above a dug entrance without charging seeds',()=>{const v=createWorld('Garden support',42,'shire-atlas-1');ensureLife(v,'homestead');const p=suggestedHome(v);v.player={...v.player,...p,yaw:.68};resetPlayerTracking(v);applyAction(v,{type:'claim',position:p});applyAction(v,{type:'life',action:{kind:'blueprint',id:'starter-smial'}});v.player.yaw=0;const before=v.supplies.carrotSeed;assert.throws(()=>applyAction(v,{type:'life',action:{kind:'blueprint',id:'garden'}}),/clear patch/);assert.equal(v.supplies.carrotSeed,before);assert.equal(v.crops.length,0)})
await check('pause freezes clock, position, crops and actors; saved settings reject duplicate keys',()=>{act({type:'life',action:{kind:'pause',value:true}});const before=JSON.stringify(w);advanceWorld(w,60);assert.equal(JSON.stringify(w),before);observePlayer(w,{...w.player,x:w.player.x+1});assert.equal(JSON.stringify(w),before);assert.throws(()=>act({type:'life',action:{kind:'settings',values:{bindings:{...w.life!.settings.bindings,forward:'KeyS'}}}}),/unique/);act({type:'life',action:{kind:'pause',value:false}})})
await check('public planting is rejected and a home restricts building to owned land',()=>{assert.throws(()=>act({type:'plant',kind:'carrot',position:{...w.player}}),/Public|public|home/);position(suggestedHome(w));act({type:'claim',position:{...w.player}});assert(w.home);assert.throws(()=>act({type:'plant',kind:'carrot',position:{x:w.player.x+100,y:w.player.y,z:w.player.z}}),/85 metres/)})
await check('paid furniture placement, removal and undo conserve materials',()=>{const p={x:w.player.x+3,y:height(w.player.x+3,w.player.z,w),z:w.player.z};const timber=itemCount(w,'wood');act({type:'furnish',kind:'chest',position:p,yaw:0});assert.equal(itemCount(w,'wood'),timber-4);const chest=w.furniture.at(-1)!;act({type:'life',action:{kind:'transfer',chest:chest.id,item:'wood',count:2,withdraw:false}});assert.throws(()=>act({type:'remove-furniture',id:chest.id}),/Empty/);assert.throws(()=>act({type:'life',action:{kind:'furniture-undo'}}),/Empty/);assert.equal(w.life!.containers[chest.id].wood,2);assert(w.furniture.some(f=>f.id===chest.id));act({type:'life',action:{kind:'transfer',chest:chest.id,item:'wood',count:2,withdraw:true}});act({type:'remove-furniture',id:chest.id});assert.equal(itemCount(w,'wood'),timber);act({type:'life',action:{kind:'furniture-undo'}});assert.equal(itemCount(w,'wood'),timber-4);assert(w.furniture.some(f=>f.id===chest.id))})
await check('garden blueprint harvest supplies cooking and consumed meals',()=>{act({type:'life',action:{kind:'blueprint',id:'garden'}});assert.equal(w.crops.length,12);advanceWorld(w,61);const carrot=w.crops.find(c=>c.kind==='carrot')!;position({...carrot.position,y:carrot.position.y+.08});act({type:'harvest',id:carrot.id});assert(itemCount(w,'carrot')>=3);enterInn();act({type:'life',action:{kind:'craft',id:'stew'}});assert.equal(itemCount(w,'stew'),1);act({type:'life',action:{kind:'eat',item:'stew'}});assert.equal(itemCount(w,'stew'),0);assert(w.life!.mealUntil>w.time)})
await check('trade, friendship, lesson and gift limits retain their results',()=>{const r=w.life!.interior!.keeper!,coins=w.life!.coins;act({type:'life',action:{kind:'trade',npc:r,item:'bread',count:1,buying:true}});assert.equal(w.life!.coins,coins-9);act({type:'life',action:{kind:'gift',id:r,item:'bread'}});assert.throws(()=>act({type:'life',action:{kind:'gift',id:r,item:'bread'}}),/already/);act({type:'life',action:{kind:'service',id:'lesson'}});assert.throws(()=>act({type:'life',action:{kind:'service',id:'lesson'}}),/tomorrow/)})
await check('observation patch is smaller and preserves static world fields',()=>{const incoming=observation(w),merged=mergeObservation(w,incoming);assert.equal(merged.edits,w.edits);assert.equal(merged.furniture,w.furniture);assert.equal(merged.combat!.actors.length,w.combat!.actors.length);assert(JSON.stringify(incoming).length<JSON.stringify(w).length*.65);validateWorld(merged)})
await check('authored adventure threats use their intended territories',()=>{act({type:'life',action:{kind:'exit'}});act({type:'life',action:{kind:'style',style:'adventure'}});const threats=w.combat!.actors.filter(a=>a.kind==='hostile'&&actorEnabled(w,a));assert.equal(threats.length,6);assert(combatActor(w,'hostile:23-barrow-wight')!.home.x>100000);assert(!actorEnabled(w,combatActor(w,'hostile:24-watcher')!));act({type:'life',action:{kind:'style',style:'homestead'}})})
await check('barrow puzzle enforces the sequence and grants its token only once',()=>{const p=storyPlaces(w)[0];position({...p.door,y:height(p.door.x,p.door.z,w)+.08});act({type:'life',action:{kind:'enter',id:p.id}});const origin=w.life!.interior!.origin;for(const [rune,x,z]of [['leaf',-3,-3],['river',0,-4],['star',3,-3]] as const){position({x:origin.x+x,y:origin.y,z:origin.z+z+2});act({type:'life',action:{kind:'barrow-rune',rune}})}assert.equal(w.life!.stats.barrowToken,1);validateWorld(w);act({type:'life',action:{kind:'exit'}})})
await check('booked and discovered ferry travel arrive at a usable landing',()=>{
  enterInn();const coins=w.life!.coins;act({type:'life',action:{kind:'use-place',id:'bucklebury-ferry'}})
  const ends=ferryCrossing(w)!;const nearLanding=(p:Point)=>ends.some(e=>Math.hypot(e.x-p.x,e.z-p.z)<1)
  assert.equal(w.life!.coins,coins-5);assert(!w.life!.interior);assert(nearLanding(w.player));assert(w.life!.discoveries.includes('bucklebury-ferry'))
  act({type:'life',action:{kind:'waypoint',id:'bucklebury-ferry'}});assert(nearLanding(w.life!.waypoint!.position))
  act({type:'travel',settlement:ATLAS_DESTINATIONS.findIndex(d=>d.id==='bucklebury-ferry')});assert(nearLanding(w.player));assert(clear(w.player,w))
})
await check('ferry crosses between two physical landings and records arrival',()=>{const ends=ferryCrossing(w)!;assert.equal(ends.length,2);position(ends[0]);act({type:'life',action:{kind:'ferry'}});advanceWorld(w,9);assert(w.life!.transport);assert(Math.hypot(w.player.x-ends[0].x,w.player.z-ends[0].z)>10);advanceWorld(w,10);assert(!w.life!.transport);assert.equal(w.life!.stats.ferryTrips,1);assert(Math.hypot(w.player.x-ends[1].x,w.player.z-ends[1].z)<1);validateWorld(w)})
await check('Hay Gate travel and directions reach the operable crossing',()=>{const v=structuredClone(w);applyAction(v,{type:'life',action:{kind:'style',style:'creative'}});applyAction(v,{type:'travel',settlement:ATLAS_DESTINATIONS.findIndex(d=>d.id==='hay-gate')});assert(clear(v.player,v));assert(Math.hypot(v.player.x-83900,v.player.z-12900)<9);applyAction(v,{type:'life',action:{kind:'waypoint',id:'hay-gate'}});assert.equal(v.life!.waypoint!.position.x,83900);applyAction(v,{type:'life',action:{kind:'gate',id:'hay-gate'}});assert(v.life!.gates!['hay-gate']);applyAction(v,{type:'life',action:{kind:'gate',id:'hay-gate'}});assert(!v.life!.gates!['hay-gate']);validateWorld(v)})
await check('life state survives atomic export, a fresh store and an independent import',async()=>{const root=path.join(evidence,'life-check-worlds');const store=new LocalWorldStore(root),loaded=await store.import(w),fresh=await new LocalWorldStore(root).read(loaded.id);assert.equal(fresh.life!.stats.barrowToken,1);assert.equal(fresh.life!.quests.welcome.state,'complete');assert.equal(fresh.life!.stats.ferryTrips,1);const exported=await store.export(loaded.id);assert.equal(exported.world.life!.residents.length,215);const corrupt=structuredClone(w);corrupt.life!.inventory.wood=-1;assert.throws(()=>validateWorld(corrupt),/life/);const invalid=structuredClone(w);invalid.life!.equipment.weapon='anything' as never;assert.throws(()=>validateLife(invalid),/character/)})
await fs.mkdir(evidence,{recursive:true});await fs.writeFile(path.join(evidence,'life-source-checks.json'),JSON.stringify({time:new Date().toISOString(),passed:results.length,results,world:{animals:w.animals.length,residents:w.life!.residents.length,quests:Object.keys(w.life!.quests).length},evidenceCategory:'source-level integration checks; does not establish browser play or user visual acceptance'},null,2));console.log(JSON.stringify({passed:results.length}))
}
main().catch(error=>{console.error(error);process.exitCode=1})
