import type { World, WorldAction } from '@shared/shire/model'
import { combatActor } from '@shared/shire/combat'

export default function CombatHud({world,targetId,busy,onAction,onStrike}:{world:World;targetId?:string;busy:boolean;onAction:(a:WorldAction)=>void;onStrike:()=>void}){
  const player=combatActor(world,'player'),target=targetId?combatActor(world,targetId):undefined
  if(!player)return null
  const v=player.vitality,dead=v.hp===0,hit=world.time-v.lastDamage<.5&&v.hp<v.maxHp
  return <><div className={`shire-combat-hud${hit?' hurt':''}`} aria-label="Health and combat"><div className="shire-vital-row"><strong>Health {Math.ceil(v.hp)} / {v.maxHp}</strong><span>{v.blockingUntil>world.time?'Guard raised':v.invulnerableUntil>world.time?'Protected':''}</span></div><meter aria-label="Player health" min="0" max={v.maxHp} value={v.hp}/><div className="shire-vital-row"><small>Stamina {Math.floor(v.stamina)}</small><small>{world.combat!.healingDraughts} healing draughts</small></div><meter className="stamina" aria-label="Player stamina" min="0" max="100" value={v.stamina}/>{v.breath<15&&<><small>Breath {Math.ceil(v.breath)}s</small><meter aria-label="Player breath" min="0" max="15" value={v.breath}/></>}{!!v.effects.length&&<small className="shire-afflictions">{v.effects.map(e=>`${e.kind==='burn'?'Burning':'Poisoned'} ${Math.ceil(e.remaining)}s`).join(' · ')}</small>}<div className="shire-row"><button disabled={busy||dead||!target||target.vitality.hp===0} onClick={onStrike}>Strike · F</button><button disabled={busy||dead} onClick={()=>onAction({type:'guard'})}>Guard · Q</button><button disabled={busy||dead||!world.combat!.healingDraughts} onClick={()=>onAction({type:'heal'})}>Heal · H</button></div>{target&&<div className="shire-target-health"><strong>{target.name}</strong><small>{Math.ceil(target.vitality.hp)} / {target.vitality.maxHp}{target.phase==='windup'?' · Attack incoming!':target.vitality.hp===0?' · Defeated':''}</small><meter aria-label="Target health" min="0" max={target.vitality.maxHp} value={target.vitality.hp}/></div>}</div>{dead&&<div className="shire-defeat" role="alert"><h2>You are defeated</h2><p>Your home and supplies remain. Recover with full health and brief protection.</p><button className="shire-primary" disabled={busy||world.time-(v.diedAt||0)<3} onClick={()=>onAction({type:'respawn'})}>Recover at home</button></div>}</>
}
