import type { World, WorldAction } from '@shared/shire/model'
import { HOSTILES, CINDERLORD_DEFINITION } from '@shared/shire/hostiles'
import { combatTactic, TACTIC_HELP } from '@shared/shire/combatTactics'
import { combatActor, actorEnabled, ADVENTURE_SITES } from '@shared/shire/combat'

export default function CreatureJournal({world,busy,onAction,onRetry}:{world:World;busy:boolean;onAction:(a:WorldAction)=>void;onRetry:()=>void}){
  const creative=!world.life||world.life.style==='creative'
  return <><div className="shire-eyebrow">CREATURES & FACTIONS</div><h2>Encounter journal</h2><p>{world.life?.style==='homestead'?'Homestead keeps your village life peaceful. Choose Adventure for authored regional encounters or Creative for the complete catalogue.':creative?'Explore the full creative catalogue from a safe overlook.':'Optional threats occupy authored territories outside the settled Shire. Prepare equipment and food before following a trail.'}</p><p className="shire-note">These encounters are game fiction. Human entries represent hostile factions; they do not describe entire peoples as evil.</p><div className="shire-creature-list">{[...HOSTILES,CINDERLORD_DEFINITION].filter(d=>{const a=combatActor(world,`hostile:${d.id}`);return a&&actorEnabled(world,a)}).map(d=>{const a=combatActor(world,`hostile:${d.id}`)!;return <article key={d.id}><h3>{d.name}</h3><p>{creative?d.description:ADVENTURE_SITES[d.id]?.description}</p><p>{TACTIC_HELP[combatTactic(world,a)]}</p><small>{d.hp} health · {d.armour} armour · {d.damageType} attacks<br/>{world.life?.defeated.includes(a.id)?'Resolved encounter · reward recorded':`${Math.round(a.home.x)} E · ${Math.round(a.home.z)} S`}</small><button disabled={busy} onClick={()=>onAction(creative?{type:'travel-encounter',id:a.id}:{type:'life',action:{kind:'waypoint',position:{...a.home,z:a.home.z+d.aggro+12},label:`${d.name} approach`}})}>{creative?'Visit':'Follow directions to'} {d.name}</button></article>})}</div><button onClick={onRetry}>Retry failed creature models</button></>
}
