'use client'
import { useCallback, useEffect, useRef, useState } from 'react'
import type { World, WorldAction, WorldSummary, Tool, FurnitureKind } from '@shared/shire/model'
import { FURNITURE, SETTLEMENTS } from '@shared/shire/model'
import { cinderlordSite } from '@shared/shire/cinderlord'
import { DEFAULT_TOOLS } from '@shared/shire/building'
import { ShireScene, ToolSettings, ViewState } from '@/game/shire/ShireScene'
import AnimalCarePanel from './AnimalCarePanel'
import './shire.css'

const initialSettings:ToolSettings={...DEFAULT_TOOLS}
const tools:Array<{id:Tool;name:string;help:string}>=[
  {id:'entrance',name:'Entry',help:'Aim into a nearby hillside. Dig a gentle descending tunnel to a level, covered chamber.'},
  {id:'room',name:'Room',help:'Inside the hill, look at a wall. The floor stays at your feet; earth must remain above the ceiling.'},
  {id:'passage',name:'Passage',help:'Connect your rooms with a narrow corridor.'},{id:'dig',name:'Sculpt',help:'Remove the translucent volume. Change the shape, dimensions and turn before applying.'},
  {id:'floor',name:'Lower floor',help:'Look down at a floor to lower and flatten it.'},{id:'ceiling',name:'Raise ceiling',help:'Look up at a ceiling to make more headroom.'},
  {id:'fill',name:'Add earth',help:'Add earth to reshape a wall or repair a hole. Step clear first.'},
]
const defaultView:ViewState={x:0,y:0,z:0,fps:0,pending:0,target:'',region:'The Shire',locked:false}
type Tab='explore'|'build'|'furnish'|'farm'|'animals'|'map'|'help'

export default function ShireGame(){
  const [world,setWorld]=useState<World|null>(null),[worlds,setWorlds]=useState<WorldSummary[]>([]),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[boot,setBoot]=useState(true)
  const [name,setName]=useState('A home in the Shire'),[tab,setTab]=useState<Tab>('explore'),[settings,setSettings]=useState<ToolSettings>(initialSettings),[view,setView]=useState<ViewState>(defaultView),[storage,setStorage]=useState('')
  const container=useRef<HTMLDivElement>(null),scene=useRef<ShireScene|null>(null),worldRef=useRef<World|null>(null),session=useRef(''),busyRef=useRef(false),actionRef=useRef<(a:WorldAction)=>void>(()=>{}),alive=useRef(true)
  const polling=useRef<Promise<void>|null>(null)
  const settingsRef=useRef(settings);settingsRef.current=settings
  const worldId=world?.id
  const adopt=useCallback((w:World,move=false)=>{worldRef.current=w;setWorld(w);scene.current?.setWorld(w,move)},[])
  const fetchJSON=useCallback(async(url:string,body?:unknown)=>{const response=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','x-shire-session':session.current}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'The local service could not complete that action.');return data},[])
  const refreshList=useCallback(async()=>{const data=await fetchJSON('/api/shire');session.current=data.session;setWorlds(data.worlds);setStorage(data.storage)},[fetchJSON])
  useEffect(()=>{alive.current=true;void refreshList().catch(e=>setError(e.message)).finally(()=>setBoot(false));return()=>{alive.current=false}},[refreshList])
  const perform=useCallback(async(action:WorldAction)=>{
    if(!worldRef.current||busyRef.current)return false
    busyRef.current=true;setBusy(true);setError('')
    try{
      await polling.current
      let w=worldRef.current
      const player=scene.current?.getPlayer()
      if(player&&action.type!=='checkpoint'&&action.type!=='return-home'&&action.type!=='travel'&&action.type!=='travel-cinderlord'){
        const saved=await fetchJSON('/api/shire',{type:'action',worldId:w.id,revision:w.revision,action:{type:'checkpoint',player}});w=saved.world;adopt(w)
      }
      const data=await fetchJSON('/api/shire',{type:'action',worldId:w.id,revision:w.revision,action});adopt(data.world,['travel','travel-cinderlord','return-home'].includes(action.type));setMessage(data.message)
      return true
    }catch(e){setError((e as Error).message);if(worldRef.current)try{const data=await fetchJSON(`/api/shire?world=${worldRef.current.id}`);adopt(data.world)}catch{};return false }
    finally{busyRef.current=false;setBusy(false)}
  },[adopt,fetchJSON])
  actionRef.current=a=>{void perform(a)}
  useEffect(()=>{const activeWorld=worldRef.current;if(!activeWorld||!container.current)return;const engine=new ShireScene(container.current,activeWorld,{view:setView,action:a=>actionRef.current(a),message:setMessage});scene.current=engine;engine.setSettings(settingsRef.current);return()=>{engine.dispose();scene.current=null}},[worldId]) // A world owns its complete renderer/input lifetime.
  useEffect(()=>{scene.current?.setSettings(settings)},[settings])
  useEffect(()=>{if(!world?.id)return;let cancelled=false;const poll=setInterval(()=>{if(busyRef.current||polling.current||!worldRef.current)return;polling.current=fetchJSON('/api/shire',{type:'observe',worldId:worldRef.current.id,player:scene.current?.getPlayer()||worldRef.current.player}).then(data=>{if(!cancelled)adopt(data.world)}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{polling.current=null})},1000);return()=>{cancelled=true;clearInterval(poll)}},[world?.id,fetchJSON,adopt])
  useEffect(()=>{const release=()=>scene.current?.releaseInput();window.addEventListener('pagehide',release);return()=>window.removeEventListener('pagehide',release)},[])
  async function start(id?:string,recover=false){setBusy(true);setError('');try{const data=id?recover?await fetchJSON('/api/shire',{type:'recover',worldId:id}):await fetchJSON(`/api/shire?world=${id}`):await fetchJSON('/api/shire',{type:'new',name,seed:42});adopt(data.world,true);setMessage(data.message||'Welcome home. Your world continues from its last save.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function chooseTab(next:Tab){setTab(next);scene.current?.releaseInput();setSettings(old=>({...old,tool:next==='build'?'entrance':next==='furnish'?'furnish':next==='farm'?'farm':'explore'}))}
  async function saveAndExit(){if(!await perform({type:'save'}))return;scene.current?.releaseInput();setWorld(null);worldRef.current=null;await refreshList()}
  async function backup(){if(!await perform({type:'save'})||!worldRef.current)return;try{const data=await fetchJSON('/api/shire',{type:'export',worldId:worldRef.current.id});setMessage(`Backup saved: ${data.backupPath}`)}catch(e){setError((e as Error).message)}}
  async function importFile(file:File){setBusy(true);try{if(file.size>4*1024*1024)throw Error('This backup is larger than the supported local world size.');const data=await fetchJSON('/api/shire',{type:'import',world:JSON.parse(await file.text())});adopt(data.world,true);setMessage(data.message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const sculpt=settings.tool==='dig'||settings.tool==='fill'
  const targetCrop=world?.crops.find(c=>c.id===view.targetId)

  if(!world)return <main className="shire-entry"><div className="shire-entry-land" aria-hidden="true"><i/><i/><i/></div><section className="shire-welcome"><div className="shire-eyebrow">GRUDGEBLOX · LOCAL WORLD</div><h1>The Middle-earth</h1><p className="shire-subtitle">A home in the Shire</p><p className="shire-intro">Find a quiet hill. Make a doorway. Let a home grow beneath the grass.</p><div className="shire-entry-features"><span>Enclosed hillside homes</span><span>Farms & animal families</span><span>Saved on this PC</span></div>{error&&<div className="shire-error" role="alert">{error}<button onClick={()=>{setError('');void refreshList().catch(e=>setError(e.message))}}>Retry</button></div>}
    <div className="shire-start"><label>Your world name<input value={name} onChange={e=>setName(e.target.value)} maxLength={60}/></label><button className="shire-primary" disabled={busy||boot||!session.current} onClick={()=>void start()}>Start a new world <span>↗</span></button></div>
    {!!worlds.length&&<div className="shire-saves"><h2>Continue your journey</h2>{worlds.map(w=><div className="shire-save" key={w.id}><div><strong>{w.name}</strong><small>{w.savedAt?new Date(w.savedAt).toLocaleString():'Original save preserved'}</small></div><button disabled={busy} onClick={()=>void start(w.id)}>Continue</button><button className="shire-quiet" disabled={busy} onClick={()=>void start(w.id,true)}>Recover previous</button></div>)}</div>}
    <label className="shire-import">Restore a backup<input type="file" accept=".json" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f)}}/></label><footer>{boot?'Opening local storage…':storage?`Local saves · ${storage}`:'Use the local Windows launcher to begin.'}<br/>Designed geography informed by retained references. Animal visuals are a work in progress.</footer></section></main>

  return <main className="shire-game"><div className="shire-viewport" ref={container}/><div className="shire-vignette"/>
    <header className="shire-topbar"><div><div className="shire-eyebrow">THE MIDDLE-EARTH</div><h1>{view.region}</h1><small>{world.name}</small></div><div className="shire-world-status"><span className="shire-status-dot"/>Local world <span>Day {Math.floor(world.time/600)+1} · {Math.floor(world.time%600/25).toString().padStart(2,'0')}:00</span><button disabled={busy} onClick={()=>void perform({type:'save'})}>{busy?'Saving…':'Save world'}</button><button className="shire-quiet" disabled={busy} onClick={()=>void saveAndExit()}>Save & leave</button></div></header>
    <div className="shire-crosshair" aria-hidden="true">+</div><div className="shire-aim"><span>{view.target||'Rolling countryside'}</span>{view.targetKind&&<small>E · {view.targetKind==='enemy'?'Strike':view.targetKind==='animal'?'Feed & care':view.targetKind==='crop'?'Water / harvest':'Use'}</small>}</div>
    <div className="shire-left"><div className="shire-compass">N<span style={{transform:`rotate(${view.locked?0:0}deg)`}}>✧</span><small>{Math.round(view.x)} E · {Math.round(view.z)} S</small></div><MiniMap x={view.x} z={view.z}/>{view.enemy&&<div className="shire-encounter-status" role="status"><strong>{view.enemy}</strong><small>E · strike nearby<br/>Dodge the orange ground-smash ring</small></div>}<button className="shire-map-open" onClick={()=>chooseTab('map')}>Open map</button></div>
    {tab==='explore'?<aside className="shire-explore-card"><div className="shire-eyebrow">MAKE YOURSELF AT HOME</div><h2>A doorway in the hillside</h2><p>Walk towards the hill beside you. Mark your home, then open an entrance and dig rooms beneath the grass.</p><button className="shire-primary" onClick={()=>scene.current?.capture()}>{view.locked?'Exploring · Esc releases the mouse':'Explore · mouse look'}</button><p className="shire-key-hint">WASD walk · Shift run · Space jump<br/>Right-drag look · E interact · Esc release</p><button onClick={()=>chooseTab('build')}>Start building</button><div className="shire-note">Development world: the retained rabbit and local resident models are reused. Other animals use labelled development representations pending accepted assets.</div></aside>:<aside className="shire-panel"><button className="shire-close" aria-label="Close panel" onClick={()=>chooseTab('explore')}>×</button>
    {tab==='build'&&<><div className="shire-eyebrow">BENEATH THE GRASS</div><h2>Shape your home</h2><p>Choose a free hill beyond the public homes. Right-drag to aim; press F or Apply tool.</p><button onClick={()=>scene.current?.claim()}>Mark this hill as home</button><div className="shire-tool-grid">{tools.map(t=><button key={t.id} className={settings.tool===t.id?'selected':''} onClick={()=>setSettings(s=>({...s,tool:t.id}))}>{t.name}</button>)}</div><p className="shire-tool-help">{tools.find(t=>t.id===settings.tool)?.help}</p>{sculpt?<><label>Shape<select value={settings.brushShape} onChange={e=>setSettings(s=>({...s,brushShape:e.target.value as ToolSettings['brushShape']}))}><option value="sphere">Ellipsoid / sphere</option><option value="box">Rounded box</option><option value="cylinder">Cylinder</option></select></label>{(['brushWidth','brushHeight','brushDepth'] as const).map((key,i)=><label key={key}>{['Width','Height','Depth'][i]} · {settings[key].toFixed(1)} m<input type="range" min="0.5" max="6" step="0.25" value={settings[key]} onChange={e=>setSettings(s=>({...s,[key]:+e.target.value}))}/></label>)}<label>Turn · {Math.round(settings.yaw*180/Math.PI)}°<input type="range" min="0" max={Math.PI*2} step={Math.PI/12} value={settings.yaw} onChange={e=>setSettings(s=>({...s,yaw:+e.target.value}))}/></label><p className="shire-note">The translucent layer shows the full sculpted volume, including the part inside the hill. All dimensions are full metres across.</p></>:<><label>Width · {settings.width.toFixed(1)} m<input type="range" min="2" max="6" step="0.5" value={settings.width} onChange={e=>setSettings(s=>({...s,width:+e.target.value}))}/></label><label>Ceiling height · {settings.height.toFixed(1)} m<input type="range" min="2.5" max="4" step="0.5" value={settings.height} onChange={e=>setSettings(s=>({...s,height:+e.target.value}))}/></label>{settings.tool!=='entrance'&&<label>Depth · {settings.depth.toFixed(1)} m<input type="range" min="1" max="6" step="0.5" value={settings.depth} onChange={e=>setSettings(s=>({...s,depth:+e.target.value}))}/></label>}</>}{view.preview&&<p className="shire-tool-help" role="status">{view.preview}</p>}<button className="shire-primary" disabled={busy||view.pending>0} onClick={()=>scene.current?.applyTool()}>Apply tool · F</button><div className="shire-row"><button disabled={busy||!world.edits.length} onClick={()=>void perform({type:'undo'})}>Undo</button><button disabled={busy||!world.redo.length} onClick={()=>void perform({type:'redo'})}>Redo</button></div><small>{world.edits.length} saved terrain edits · earth remains above enclosed rooms</small></>}
    {tab==='furnish'&&<><div className="shire-eyebrow">THE COMFORTS OF HOME</div><h2>Furnish & settle</h2><p>Look at a floor. The translucent area shows the placement. Doors measure both hallway walls and the ceiling, then fill the surrounding gaps.</p><div className="shire-tool-grid">{Object.entries(FURNITURE).map(([id,f])=><button key={id} className={settings.furniture===id?'selected':''} onClick={()=>setSettings(s=>({...s,furniture:id as FurnitureKind}))}>{f.label}</button>)}</div><label>Turn · {Math.round(settings.yaw*180/Math.PI)}°<input type="range" min="0" max={Math.PI*2} step={Math.PI/12} value={settings.yaw} onChange={e=>setSettings(s=>({...s,yaw:+e.target.value}))}/></label><button className="shire-primary" disabled={busy} onClick={()=>scene.current?.applyTool()}>Place furnishing · F</button>{view.targetKind==='furniture'&&<div className="shire-row"><button onClick={()=>scene.current?.interact()}>Use {view.target}</button><button onClick={()=>void perform({type:'remove-furniture',id:view.targetId!})}>Remove</button></div>}<p className="shire-note">Wildlife feeder: use to add up to 12 feed. Bird perch and rabbit shelter: use to open or close access. Place them outdoors near the animals. Lanterns switch on and off.</p><h3>Household storage</h3><p>Stand beside your chest to store or collect produce. Beds let you rest; doors open with E.</p><div className="shire-row"><button onClick={()=>void perform({type:'store'})}>Store produce</button><button onClick={()=>void perform({type:'withdraw'})}>Take produce</button></div><small>In storage: {world.storage.barley} barley · {world.storage.carrot} carrots</small></>}
    {tab==='farm'&&<><div className="shire-eyebrow">FROM SOIL TO TABLE</div><h2>Tend your garden</h2><p>Look at dry outdoor ground to till and plant. Water each seed, let it grow, then harvest.</p><div className="shire-row"><button className={settings.crop==='barley'?'selected':''} onClick={()=>setSettings(s=>({...s,crop:'barley'}))}>Barley</button><button className={settings.crop==='carrot'?'selected':''} onClick={()=>setSettings(s=>({...s,crop:'carrot'}))}>Carrots</button></div><button className="shire-primary" onClick={()=>scene.current?.applyTool()}>Till & plant · F</button>{targetCrop&&<div className="shire-row"><button onClick={()=>void perform({type:'water',id:targetCrop.id})}>Water crop</button><button onClick={()=>void perform({type:'harvest',id:targetCrop.id})}>Harvest crop</button></div>}<h3>Your supplies</h3><dl className="shire-inventory"><dt>Barley seeds</dt><dd>{world.supplies.barleySeed}</dd><dt>Carrot seeds</dt><dd>{world.supplies.carrotSeed}</dd><dt>Barley / carrots</dt><dd>{world.supplies.barley} / {world.supplies.carrot}</dd><dt>Animal feed</dt><dd>{world.supplies.feed}</dd></dl><p className="shire-note">A watered crop ripens after 60 seconds of play. Harvesting returns seed, produce and animal feed. Growth pauses when the game is closed.</p></>}
    {tab==='animals'&&<AnimalCarePanel world={world} position={view} busy={busy} onFeed={id=>void perform({type:'feed',id})} onBreed={(dam,sire)=>void perform({type:'breed',dam,sire})} onReact={(id,type)=>void perform({type,id})}/>}
    {tab==='map'&&<><div className="shire-eyebrow">ROOM TO ROAM</div><h2>Your countryside</h2><LargeMap x={view.x} z={view.z} site={cinderlordSite(world)}/><p>Four kilometres across. The Shire settlements, roads and hill shapes here are designed layouts, not measured Tolkien map coordinates.</p>{SETTLEMENTS.map((s,i)=><button className="shire-destination" key={s.name} onClick={()=>void perform({type:'travel',settlement:i})}><span>{s.name}</span><small>{s.elves?'Fangorn · creative elven settlement':'Shire · inhabited neighbourhood'}</small></button>)}<button className="shire-destination" disabled={busy} onClick={()=>void perform({type:'travel-cinderlord'})}><span>Ashen Hollow · Cinderlord</span><small>Hostile magma guardian · travel to a safe overlook</small></button><button onClick={()=>void perform({type:'return-home'})}>Return to home marker</button><p className="shire-note">Walking also connects every area. Fangorn’s elves follow Al’s creative choice.</p></>}
    {tab==='help'&&<><div className="shire-eyebrow">A FEW USEFUL THINGS</div><h2>Make a home</h2><ol><li>Walk to a hillside outside the public village and mark it as home.</li><li>Use Entry while aiming into a hill. Follow the descending tunnel into its level chamber.</li><li>Dig a Room deeper into the hill; connect more rooms with Passage.</li><li>Lower floors or raise ceilings, then add furniture. Keep a clear exit.</li><li>Plant outside, water and harvest. Feed and breed the farm animals.</li></ol><h3>Controls</h3><p>WASD walk · Shift run · Space jump<br/>Right-drag look · Arrow keys turn/move<br/>Page Up/Down aim · F apply · E interact<br/>Esc releases all captured input</p><h3>Backups & recovery</h3><button onClick={()=>void backup()}>Export backup to E:</button><button onClick={()=>void perform({type:'return-home'})}>Recover to home marker</button><p>Every accepted action is written to E:. Save & leave records your current position. A damaged save can be recovered into a separate slot from the welcome screen.</p><h3>Sources & asset boundaries</h3><p>The retained peoples workbook and atlas/races reports inform this project. A measured geometric map and fauna database remain unverified. Exact source hashes and animal package provenance are retained beside local assets.</p><p className="shire-note">Local residents reuse GrudgeBlox’s existing kit. The previously approved Grudge rabbit is reused with its retained evidence. Other animal representations are development visuals pending accepted packages.</p></>}
    </aside>}
    {(message||error)&&<div className={`shire-toast ${error?'error':''}`} role={error?'alert':'status'}><span>{error||message}</span><button aria-label="Dismiss message" onClick={()=>{setMessage('');setError('')}}>×</button></div>}
    <nav className="shire-bottom" aria-label="World activities">{(['explore','build','furnish','farm','animals','map','help'] as Tab[]).map((t,i)=><button className={tab===t?'active':''} key={t} onClick={()=>chooseTab(t)}><span>{['⌂','⌑','▤','❧','♧','◇','?'][i]}</span>{t[0].toUpperCase()+t.slice(1)}</button>)}<div className="shire-save-state">{view.pending?`Shaping ${view.pending} terrain pieces…`:`Saved revision ${world.revision}`}<small>{view.fps} fps · local on E:</small></div></nav>
  </main>
}
function MiniMap({x,z}:{x:number;z:number}){return <svg className="shire-minimap" viewBox="0 0 160 160" aria-label="Nearby landscape map"><rect width="160" height="160" fill="#c1c49b"/><path d="M0 28Q80 0 160 42M0 67Q80 38 160 75M0 113Q80 75 160 125" fill="none" stroke="#9fa573" strokeWidth="9"/><ellipse cx={80+(25-x)/3} cy={80+(114-z)/3} rx="7" ry="14" fill="#87a7a0"/>{SETTLEMENTS.map(s=><g key={s.name} transform={`translate(${80+(s.x-x)/3},${80+(s.z-z)/3})`}><circle r="7" fill="#9a7a52"/></g>)}<circle cx="80" cy="80" r="5" fill="#f3ead0" stroke="#354d38" strokeWidth="2"/><text x="80" y="14" textAnchor="middle" fill="#394c35" fontSize="10">N</text></svg>}
function LargeMap({x,z,site}:{x:number;z:number;site:{x:number;z:number}}){const map=(n:number)=>150+n/14;return <svg className="shire-large-map" viewBox="0 0 300 300" aria-label="Designed Shire and Fangorn map"><rect width="300" height="300" rx="10" fill="#bfc59b"/><path d="M12 45Q95 15 210 60M4 105Q150 55 300 135M0 215Q130 140 296 255" fill="none" stroke="#a0ad7c" strokeWidth="20"/><path d="M230 228Q285 205 299 290L299 299H218Z" fill="#516f4a"/>{SETTLEMENTS.slice(1).map(s=><line key={s.name} x1={map(55)} y1={map(30)} x2={map(s.x)} y2={map(s.z)} stroke="#e7dbab" strokeWidth="3"/>)}{SETTLEMENTS.map(s=><g key={s.name}><circle cx={map(s.x)} cy={map(s.z)} r="4" fill="#715633"/><text x={map(s.x)} y={map(s.z)-8} textAnchor="middle" fontSize="9" fill="#2f442d">{s.name}</text></g>)}<g><circle cx={map(site.x)} cy={map(site.z)} r="5" fill="#a13d22"/><text x={map(site.x)} y={map(site.z)-9} textAnchor="middle" fontSize="9" fill="#6e2819">Ashen Hollow</text></g><circle cx={map(x)} cy={map(z)} r="4" fill="#fff7db" stroke="#304d36" strokeWidth="2"/><text x="15" y="22" fill="#41513a" fontSize="11">N ↑</text><text x="15" y="286" fill="#41513a" fontSize="9">4 km · designed geography</text></svg>}
