'use client'
import { useCallback, useEffect, useRef, useState } from 'react'
import type { World, WorldAction, WorldSummary, Tool, FurnitureKind } from '@shared/shire/model'
import { FURNITURE, SETTLEMENTS } from '@shared/shire/model'
import { cinderlordSite } from '@shared/shire/cinderlord'
import { DEFAULT_TOOLS } from '@shared/shire/building'
import { ShireScene, ToolSettings, ViewState } from '@/game/shire/ShireScene'
import AtlasMap from './AtlasMap'
import { isAtlas, ATLAS_DESTINATIONS, townPlots } from '@shared/shire/atlas'
import AnimalCarePanel from './AnimalCarePanel'
import './shire.css'
import CreatureJournal from './CreatureJournal'
import CombatHud from './CombatHud'
import { keyLabel } from './controlLabels'
import LifePanel, { type LifeTab } from './LifePanel'
import TouchControls from './TouchControls'
import WaypointHud from './WaypointHud'
import { PLAY_STYLES, QUESTS } from '@shared/shire/lifeContent'
import { mergeObservation } from '@shared/shire/observation'
import type { PlayStyle } from '@shared/shire/lifeTypes'

const initialSettings:ToolSettings={...DEFAULT_TOOLS}
const tools:Array<{id:Tool;name:string;help:string}>=[
  {id:'entrance',name:'Entry',help:'Aim into a nearby hillside. Dig a gentle descending tunnel to a level, covered chamber.'},
  {id:'room',name:'Room',help:'Inside the hill, look at a wall. The floor stays at your feet; earth must remain above the ceiling.'},
  {id:'passage',name:'Passage',help:'Connect your rooms with a narrow corridor.'},{id:'dig',name:'Sculpt',help:'Remove the translucent volume. Change the shape, dimensions and turn before applying.'},
  {id:'floor',name:'Lower floor',help:'Look down at a floor to lower and flatten it.'},{id:'ceiling',name:'Raise ceiling',help:'Look up at a ceiling to make more headroom.'},
  {id:'fill',name:'Add earth',help:'Add earth to reshape a wall or repair a hole. Step clear first.'},
]
const defaultView:ViewState={x:0,y:0,z:0,fps:0,pending:0,target:'',region:'The Shire',locked:false}
type Tab='explore'|'build'|'furnish'|'farm'|'animals'|'map'|'help'|'creatures'|LifeTab

export default function ShireGame(){
  const [world,setWorld]=useState<World|null>(null),[worlds,setWorlds]=useState<WorldSummary[]>([]),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[boot,setBoot]=useState(true)
  const [playStyle,setPlayStyle]=useState<PlayStyle>('homestead'),[seed,setSeed]=useState(42),[generator,setGenerator]=useState<World['generator']>('shire-atlas-1'),[saveFilter,setSaveFilter]=useState(''),[includeArchived,setIncludeArchived]=useState(false)
  const [selectedResident,setSelectedResident]=useState('')
  const [overview,setOverview]=useState(false),[destination,setDestination]=useState('0')
  const [name,setName]=useState('A home in the Shire'),[tab,setTab]=useState<Tab>('explore'),[settings,setSettings]=useState<ToolSettings>(initialSettings),[view,setView]=useState<ViewState>(defaultView),[storage,setStorage]=useState('')
  const container=useRef<HTMLDivElement>(null),scene=useRef<ShireScene|null>(null),worldRef=useRef<World|null>(null),session=useRef(''),busyRef=useRef(false),actionRef=useRef<(a:WorldAction)=>void>(()=>{}),alive=useRef(true)
  const polling=useRef<Promise<void>|null>(null)
  const settingsRef=useRef(settings);settingsRef.current=settings
  const worldId=world?.id
  const adopt=useCallback((w:World,move=false)=>{worldRef.current=w;setWorld(w);scene.current?.setWorld(w,move)},[])
  const fetchJSON=useCallback(async(url:string,body?:unknown)=>{const response=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','x-shire-session':session.current}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'The local service could not complete that action.');return data},[])
  const refreshList=useCallback(async()=>{const data=await fetchJSON('/api/shire');session.current=data.session;setWorlds(data.worlds);setStorage(data.storage)},[fetchJSON])
  useEffect(()=>{alive.current=true;void refreshList().catch(e=>setError(e.message)).finally(()=>setBoot(false));return()=>{alive.current=false}},[refreshList])
  const perform=useCallback(async(action:WorldAction)=>{
    if(!worldRef.current||busyRef.current)return false
    busyRef.current=true;setBusy(true);setError('')
    try{
      await polling.current
      let w=worldRef.current
      const player=scene.current?.getPlayer()
      if(player&&action.type!=='checkpoint'&&action.type!=='return-home'&&action.type!=='travel'&&action.type!=='travel-cinderlord'&&action.type!=='travel-encounter'&&action.type!=='respawn'){
        const saved=await fetchJSON('/api/shire',{type:'action',worldId:w.id,revision:w.revision,action:{type:'checkpoint',player}});w=saved.world;adopt(w)
      }
      const data=await fetchJSON('/api/shire',{type:'action',worldId:w.id,revision:w.revision,action});adopt(data.world,['travel','travel-cinderlord','return-home','travel-encounter','respawn'].includes(action.type)||action.type==='life'&&['enter','exit','use-place','dismount'].includes(action.action.kind));setMessage(data.message);if(action.type==='life'&&['talk','enter'].includes(action.action.kind)){scene.current?.releaseInput();setSelectedResident(action.action.kind==='talk'?action.action.id:data.world.life?.interior?.keeper||'');setTab('village');setSettings(s=>({...s,tool:'explore'}))}
      return true
    }catch(e){setError((e as Error).message);if(worldRef.current)try{const data=await fetchJSON(`/api/shire?world=${worldRef.current.id}`);adopt(data.world)}catch{};return false }
    finally{busyRef.current=false;setBusy(false)}
  },[adopt,fetchJSON])
  actionRef.current=a=>{void perform(a)}
  useEffect(()=>{const activeWorld=worldRef.current;if(!activeWorld||!container.current)return;const engine=new ShireScene(container.current,activeWorld,{view:setView,action:a=>actionRef.current(a),message:setMessage,activity:next=>{engine.releaseInput();setTab(next);setSettings(s=>({...s,tool:'explore'}))}});scene.current=engine;if(new URLSearchParams(location.search).has('combatQA'))Object.defineProperty(window,'shireCombatQA',{configurable:true,value:{snapshot:()=>({world:structuredClone(worldRef.current),view:engine.getCombatDiagnostics(),player:engine.getPlayer(),performance:engine.getPerformanceDiagnostics(),drawCalls:engine.renderer.info.render.calls})}});engine.setSettings(settingsRef.current);return()=>{engine.dispose();scene.current=null;delete (window as Window&{shireCombatQA?:unknown}).shireCombatQA}},[worldId]) // A world owns its complete renderer/input lifetime.
  useEffect(()=>{scene.current?.setSettings(settings)},[settings])
  useEffect(()=>{if(!world?.id)return;let cancelled=false;const poll=setInterval(()=>{if(busyRef.current||polling.current||!worldRef.current)return;polling.current=fetchJSON('/api/shire',{type:'observe',worldId:worldRef.current.id,player:scene.current?.getPlayer()||worldRef.current.player,revision:worldRef.current.revision}).then(data=>{if(!cancelled&&worldRef.current)adopt(data.world||mergeObservation(worldRef.current,data.observation))}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{polling.current=null})},250);return()=>{cancelled=true;clearInterval(poll)}},[world?.id,fetchJSON,adopt])
  useEffect(()=>{const release=()=>scene.current?.releaseInput();window.addEventListener('pagehide',release);return()=>window.removeEventListener('pagehide',release)},[])
  async function start(id?:string,recover=false){setBusy(true);setError('');try{const data=id?recover?await fetchJSON('/api/shire',{type:'recover',worldId:id}):await fetchJSON(`/api/shire?world=${id}`):await fetchJSON('/api/shire',{type:'new',name,seed,style:playStyle,generator});setOverview(false);adopt(data.world,true);setMessage(data.message||'Welcome home. Your world continues from its last save.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function chooseTab(next:Tab){setTab(next);scene.current?.releaseInput();setSettings(old=>({...old,tool:next==='build'?'entrance':next==='furnish'?'furnish':next==='farm'?'farm':'explore'}))}
  async function saveAndExit(){if(!await perform({type:'save'}))return;scene.current?.releaseInput();setWorld(null);worldRef.current=null;await refreshList()}
  async function backup(){if(!await perform({type:'save'})||!worldRef.current)return;try{const data=await fetchJSON('/api/shire',{type:'export',worldId:worldRef.current.id});setMessage(`Backup saved: ${data.backupPath}`)}catch(e){setError((e as Error).message)}}
  async function importFile(file:File){setBusy(true);try{if(file.size>4*1024*1024)throw Error('This backup is larger than the supported local world size.');const data=await fetchJSON('/api/shire',{type:'import',world:JSON.parse(await file.text())});adopt(data.world,true);setMessage(data.message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  useEffect(()=>{if(!worldId)return;const pause=()=>{if(worldRef.current?.life?.settings.autoPause&&!worldRef.current.life.paused)actionRef.current({type:'life',action:{kind:'pause',value:true}})};const visibility=()=>{if(document.hidden)pause()};window.addEventListener('blur',pause);document.addEventListener('visibilitychange',visibility);return()=>{window.removeEventListener('blur',pause);document.removeEventListener('visibilitychange',visibility)}},[worldId])
  const sculpt=settings.tool==='dig'||settings.tool==='fill'
  const targetCrop=world?.crops.find(c=>c.id===view.targetId)

  if(!world)return <main className="shire-entry"><div className="shire-entry-land" aria-hidden="true"><i/><i/><i/></div><section className="shire-welcome"><div className="shire-eyebrow">GRUDGEBLOX · LOCAL WORLD</div><h1>The Shire</h1><p className="shire-subtitle">There is a place for you here.</p><p className="shire-intro">Make a hillside home, grow a garden, get to know your neighbours, and discover the country beyond the lanes.</p><div className="shire-entry-features"><span>A living village</span><span>Your home & household</span><span>Saved on this PC</span></div>{error&&<div className="shire-error" role="alert">{error}<button onClick={()=>{setError('');void refreshList().catch(e=>setError(e.message))}}>Retry</button></div>}
    <div className="shire-play-styles" role="group" aria-label="Play style">{Object.entries(PLAY_STYLES).map(([id,s])=><button key={id} aria-pressed={playStyle===id} className={playStyle===id?'selected':''} onClick={()=>setPlayStyle(id as PlayStyle)}><strong>{s.name}</strong><small>{s.description}</small></button>)}</div><details className="shire-world-options"><summary>World options</summary><label>Seed<input type="number" value={seed} onChange={e=>setSeed(Math.round(+e.target.value))}/></label><label>Landscape<select value={generator} onChange={e=>setGenerator(e.target.value as World['generator'])}><option value="shire-atlas-1">The Shire & Bree-land atlas</option><option value="shire-1">Original compact creative countryside</option></select></label></details><div className="shire-start"><label>Your world name<input value={name} onChange={e=>setName(e.target.value)} maxLength={60}/></label><button className="shire-primary" disabled={busy||boot||!session.current} onClick={()=>void start()}>Start a new world <span>↗</span></button></div>
    {!!worlds.length&&<div className="shire-saves"><h2>Continue your journey</h2><input aria-label="Find a saved world" placeholder="Find a saved world" value={saveFilter} onChange={e=>setSaveFilter(e.target.value)}/><label className="shire-check"><input type="checkbox" checked={includeArchived} onChange={e=>setIncludeArchived(e.target.checked)}/> Include archived worlds</label>{worlds.filter(w=>(includeArchived||!w.archived)&&w.name.toLowerCase().includes(saveFilter.toLowerCase())).map(w=><div className="shire-save" key={w.id}><div><strong>{w.name}</strong><small>{w.savedAt?new Date(w.savedAt).toLocaleString()+(w.style?' · '+PLAY_STYLES[w.style].name:' · original world')+(w.archived?' · archived':''):'Original save preserved'}</small></div><button disabled={busy} onClick={()=>void start(w.id)}>Continue</button><button className="shire-quiet" disabled={busy} onClick={()=>void start(w.id,true)}>Recover previous</button></div>)}</div>}
    <label className="shire-import">Restore a backup<input type="file" accept=".json" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f)}}/></label><footer>{boot?'Opening local storage…':storage?`Local saves · ${storage}`:'Use the local Windows launcher to begin.'}<br/>Atlas geography with designed local elevations, households and activities. Your existing worlds and their backups remain available.</footer></section></main>

  return <main className={`shire-game${overview?' shire-overview':''}${world.life?.paused?' shire-is-paused':''}${world.life?.settings.contrast?' shire-high-contrast':''}`} style={{'--shire-ui-scale':world.life?.settings.uiScale||1} as React.CSSProperties}><div className="shire-viewport" ref={container}/><div className="shire-vignette"/>
    <header className="shire-topbar"><div><div className="shire-eyebrow">THE MIDDLE-EARTH</div><h1>{view.region}</h1><small>{world.name} · {world.life?PLAY_STYLES[world.life.style].name:''}</small></div><div className="shire-world-status"><span className="shire-status-dot"/>Local world <span>Day {Math.floor(world.time/600)+1} · {Math.floor(world.time%600/25).toString().padStart(2,'0')}:00</span><button disabled={busy} onClick={()=>void perform({type:'life',action:{kind:'pause',value:!world.life?.paused}})}>{world.life?.paused?'Resume':'Pause'}</button><button disabled={busy} onClick={()=>void perform({type:'save'})}>{busy?'Saving…':'Save world'}</button><button className="shire-quiet" disabled={busy} onClick={()=>void saveAndExit()}>Save & leave</button></div></header>
    {typeof location!=='undefined'&&new URLSearchParams(location.search).has('combatQA')&&<details className="shire-qa"><summary>Combat verification controls</summary><button onClick={()=>scene.current?.qaFace()}>Face nearest encounter</button><button onClick={()=>scene.current?.qaFace('resident')}>Face nearest resident</button><button onClick={()=>scene.current?.qaFace('animal')}>Face nearest animal</button><button onClick={()=>scene.current?.qaDive()}>Dive for 6 seconds</button><button onClick={()=>scene.current?.qaWalk(4)}>Walk forward for 4 seconds</button><button onClick={()=>scene.current?.qaWalk(1)}>Walk forward for 1 second</button><button onClick={()=>scene.current?.qaWalk(3,true)}>Retreat for 3 seconds</button><button onClick={()=>scene.current?.releaseInput()}>Stop walking</button></details>}{world.life?.style!=='homestead'&&<CombatHud world={world} targetId={view.targetId} busy={busy} onAction={a=>void perform(a)} onStrike={()=>scene.current?.strike()}/>}<div className="shire-crosshair" aria-hidden="true">+</div><div className="shire-aim"><span>{world.life?.interior&&(!view.target||view.target==='Rolling countryside')?(world.life.interior.kind==='barrow'?'Ancient chamber':'Common room'):view.target||'Rolling countryside'}</span>{view.targetKind&&<small>{keyLabel(world,'interact')} · {view.targetKind==='enemy'?'Strike':view.targetKind==='animal'?'Feed & care':view.targetKind==='resident'?'Greet':view.targetKind==='crop'?'Water / harvest':'Use'}</small>}</div>
    <div className="shire-left" hidden={!!world.life?.interior}><div className="shire-compass">N<span style={{transform:`rotate(${(view.yaw||0)*180/Math.PI}deg)`}}>✧</span><small>{Math.round(view.x)} E · {Math.round(view.z)} S</small></div>{isAtlas(world)?<AtlasMap x={view.x} z={view.z} near/>:<MiniMap x={view.x} z={view.z}/>}{view.enemy&&<div className="shire-encounter-status" role="status"><strong>{view.enemy}</strong><small>{keyLabel(world,'apply')} · strike nearby<br/>Dodge the orange ground-smash ring</small></div>}<button className="shire-map-open" onClick={()=>chooseTab('map')}>Open map</button>{isAtlas(world)&&<button className="shire-map-open" onClick={()=>{const next=!overview;setOverview(next);if(scene.current){scene.current.overview=next;scene.current.landmarkView=false;scene.current.releaseInput()}}}>{overview?'Return to walking':'Area overview'}</button>}{isAtlas(world)&&<button className="shire-map-open" onClick={()=>{setOverview(true);if(scene.current){scene.current.overview=true;scene.current.landmarkView=true;scene.current.releaseInput()}}}>Landmark view</button>}</div>
    {world.life?.paused&&<div className="shire-pause-card"><h2>A quiet moment</h2><p>The world is paused.</p><button className="shire-primary" onClick={()=>void perform({type:'life',action:{kind:'pause',value:false}})}>Resume</button><button onClick={()=>chooseTab('settings')}>Settings</button></div>}
    {world.life?.waypoint&&!world.life.interior&&!overview&&<WaypointHud world={world} view={view} onFace={()=>scene.current?.faceWaypoint()}/>}
    {tab==='explore'?<aside className="shire-explore-card"><div className="shire-eyebrow">{world.life?.interior?.kind==='barrow'?'BENEATH THE DOWNS':world.life?.interior?'A WELCOME INSIDE':'WELCOME, NEIGHBOUR'}</div><h2>{world.life?.interior?.label||world.life?.avatar.name||'A home in the Shire'}</h2><p>{world.life?.interior?.kind==='barrow'?'First the growing leaf, then the running river, and last the guiding star. Select the stones, or open Village for their controls.':world.life?.interior?'Explore the room, speak with the host or use the kitchen and workbench.':nextObjective(world)}</p><button className="shire-primary" onClick={()=>scene.current?.capture()}>{view.locked?'Exploring':'Explore · mouse look'}</button>{view.targetKind&&<button disabled={busy} onClick={()=>scene.current?.interact()}>Use {view.target}</button>}<div className="shire-row"><button onClick={()=>chooseTab('journal')}>Journal</button><button onClick={()=>chooseTab('inventory')}>Satchel</button></div><p className="shire-key-hint">Walk · {world.life?.settings.bindings.forward.replace('Key','')}/{world.life?.settings.bindings.left.replace('Key','')}/{world.life?.settings.bindings.back.replace('Key','')}/{world.life?.settings.bindings.right.replace('Key','')} · Interact · {world.life?.settings.bindings.interact.replace('Key','')}<br/>Right-drag to look · Both mouse buttons walk<br/>Right-click ground to walk there · Esc pauses</p>{world.life?.interior&&<button onClick={()=>void perform({type:'life',action:{kind:'exit'}})}>Step outside</button>}{world.life?.riding&&<button onClick={()=>void perform({type:'life',action:{kind:'dismount'}})}>Dismount pony</button>}{world.life?.seated&&<button onClick={()=>void perform({type:'life',action:{kind:'stand'}})}>Stand up</button>}</aside>:<aside className="shire-panel"><button className="shire-close" aria-label="Close panel" onClick={()=>chooseTab('explore')}>×</button>
    {world.life&&(['journal','inventory','village','household','settings'] as string[]).includes(tab)&&<LifePanel key={world.id+tab} world={world} position={view} busy={busy} tab={tab as LifeTab} selectedResident={selectedResident} onAction={a=>void perform(a)}/>}
    {tab==='build'&&<><div className="shire-eyebrow">BENEATH THE GRASS</div><h2>Shape your home</h2><p>Choose a free hill beyond the public homes. Right-drag to aim; press {keyLabel(world,'apply')} or Apply tool.</p><button onClick={()=>scene.current?.claim()}>Mark this hill as home</button><div className="shire-tool-grid">{tools.map(t=><button key={t.id} className={settings.tool===t.id?'selected':''} onClick={()=>setSettings(s=>({...s,tool:t.id}))}>{t.name}</button>)}</div><p className="shire-tool-help">{tools.find(t=>t.id===settings.tool)?.help}</p>{sculpt?<><label>Shape<select value={settings.brushShape} onChange={e=>setSettings(s=>({...s,brushShape:e.target.value as ToolSettings['brushShape']}))}><option value="sphere">Ellipsoid / sphere</option><option value="box">Rounded box</option><option value="cylinder">Cylinder</option></select></label>{(['brushWidth','brushHeight','brushDepth'] as const).map((key,i)=><label key={key}>{['Width','Height','Depth'][i]} · {settings[key].toFixed(1)} m<input type="range" min="0.5" max="6" step="0.25" value={settings[key]} onChange={e=>setSettings(s=>({...s,[key]:+e.target.value}))}/></label>)}<label>Turn · {Math.round(settings.yaw*180/Math.PI)}°<input type="range" min="0" max={Math.PI*2} step={Math.PI/12} value={settings.yaw} onChange={e=>setSettings(s=>({...s,yaw:+e.target.value}))}/></label><p className="shire-note">The translucent layer shows the full sculpted volume, including the part inside the hill. All dimensions are full metres across.</p></>:<><label>Width · {settings.width.toFixed(1)} m<input type="range" min="2" max="6" step="0.5" value={settings.width} onChange={e=>setSettings(s=>({...s,width:+e.target.value}))}/></label><label>Ceiling height · {settings.height.toFixed(1)} m<input type="range" min="2.5" max="4" step="0.5" value={settings.height} onChange={e=>setSettings(s=>({...s,height:+e.target.value}))}/></label>{settings.tool!=='entrance'&&<label>Depth · {settings.depth.toFixed(1)} m<input type="range" min="1" max="6" step="0.5" value={settings.depth} onChange={e=>setSettings(s=>({...s,depth:+e.target.value}))}/></label>}</>}{view.preview&&<p className="shire-tool-help" role="status">{view.preview}</p>}<button className="shire-primary" disabled={busy||view.pending>0} onClick={()=>scene.current?.applyTool()}>Apply tool · {keyLabel(world,'apply')}</button><div className="shire-row"><button disabled={busy||!world.edits.length} onClick={()=>void perform({type:'undo'})}>Undo</button><button disabled={busy||!world.redo.length} onClick={()=>void perform({type:'redo'})}>Redo</button></div><small>{world.edits.length} saved terrain edits · earth remains above enclosed rooms</small></>}
    {tab==='furnish'&&<><div className="shire-eyebrow">THE COMFORTS OF HOME</div><h2>Furnish & settle</h2><p>Look at a floor. The translucent area shows the placement. Doors measure both hallway walls and the ceiling, then fill the surrounding gaps.</p><div className="shire-tool-grid">{Object.entries(FURNITURE).map(([id,f])=><button key={id} className={settings.furniture===id?'selected':''} onClick={()=>setSettings(s=>({...s,furniture:id as FurnitureKind}))}>{f.label}</button>)}</div><label>Turn · {Math.round(settings.yaw*180/Math.PI)}°<input type="range" min="0" max={Math.PI*2} step={Math.PI/12} value={settings.yaw} onChange={e=>setSettings(s=>({...s,yaw:+e.target.value}))}/></label><button className="shire-primary" disabled={busy} onClick={()=>scene.current?.applyTool()}>Place furnishing · {keyLabel(world,'apply')}</button>{settings.furniture!=='door'&&<button disabled={busy} onClick={()=>scene.current?.furnishAhead()}>Place on the floor ahead</button>}{view.targetKind==='furniture'&&<div className="shire-row"><button onClick={()=>scene.current?.interact()}>Use {view.target}</button><button onClick={()=>void perform({type:'remove-furniture',id:view.targetId!})}>Remove</button></div>}<p className="shire-note">Wildlife feeder: use to add up to 12 feed. Bird perch and rabbit shelter: use to open or close access. Place them outdoors near the animals. Lanterns switch on and off.</p><h3>Household storage</h3><p>Stand beside your chest to store or collect produce. Beds let you rest; doors open with {keyLabel(world,'interact')}.</p><div className="shire-row"><button onClick={()=>void perform({type:'store'})}>Store produce</button><button onClick={()=>void perform({type:'withdraw'})}>Take produce</button></div><small>In storage: {world.storage.barley} barley · {world.storage.carrot} carrots</small></>}
    {tab==='farm'&&<><div className="shire-eyebrow">FROM SOIL TO TABLE</div><h2>Tend your garden</h2><p>Look at dry outdoor ground to till and plant. Water each seed, let it grow, then harvest.</p><div className="shire-row"><button className={settings.crop==='barley'?'selected':''} onClick={()=>setSettings(s=>({...s,crop:'barley'}))}>Barley</button><button className={settings.crop==='carrot'?'selected':''} onClick={()=>setSettings(s=>({...s,crop:'carrot'}))}>Carrots</button></div><button className="shire-primary" onClick={()=>scene.current?.applyTool()}>Till & plant · {keyLabel(world,'apply')}</button>{targetCrop&&<div className="shire-row"><button onClick={()=>void perform({type:'water',id:targetCrop.id})}>Water crop</button><button onClick={()=>void perform({type:'harvest',id:targetCrop.id})}>Harvest crop</button></div>}<details open><summary>Nearby garden</summary>{world.crops.filter(c=>!c.harvested&&Math.hypot(c.position.x-view.x,c.position.z-view.z)<8).map(c=><button className="shire-destination" key={c.id} disabled={busy||Math.hypot(c.position.x-view.x,c.position.z-view.z)>6||c.watered&&world.time-c.planted<60} onClick={()=>void perform({type:c.watered?'harvest':'water',id:c.id})}>{c.watered?world.time-c.planted>=60?'Harvest':'Growing':'Water'} {c.kind} · {Math.round(Math.hypot(c.position.x-view.x,c.position.z-view.z))} m</button>)}</details><h3>Your supplies</h3><dl className="shire-inventory"><dt>Barley seeds</dt><dd>{world.supplies.barleySeed}</dd><dt>Carrot seeds</dt><dd>{world.supplies.carrotSeed}</dd><dt>Barley / carrots</dt><dd>{world.supplies.barley} / {world.supplies.carrot}</dd><dt>Animal feed</dt><dd>{world.supplies.feed}</dd></dl><p className="shire-note">A watered crop ripens after 60 seconds of play. Harvesting returns seed, produce and animal feed. Growth pauses when the game is closed.</p></>}
    {tab==='animals'&&<AnimalCarePanel world={world} position={view} busy={busy} onFeed={id=>void perform({type:'feed',id})} onBreed={(dam,sire)=>void perform({type:'breed',dam,sire})} onReact={(id,type)=>void perform({type,id})} onDirections={animal=>void perform({type:'life',action:{kind:'waypoint',position:animal.position,label:animal.name}})}/>}
    {tab==='map'&&(isAtlas(world)?<><div className="shire-eyebrow">THE SHIRE & BREE-LAND · T.A. 3018</div><h2>Your atlas</h2><AtlasMap x={view.x} z={view.z}/><p>Full regional distances, rivers and rolling terrain. Elevations and town layouts are designed interpretations of the books.</p><label>Travel to<select value={destination} onChange={e=>setDestination(e.target.value)}>{ATLAS_DESTINATIONS.map((s,i)=><option key={s.id} value={i}>{s.name}</option>)}</select></label><button className="shire-primary" disabled={busy||world.life?.style!=='creative'&&!world.life?.discoveries.includes(ATLAS_DESTINATIONS[Number(destination)].id)} onClick={()=>{void perform({type:'travel',settlement:Number(destination)}).then(ok=>{if(ok)chooseTab('explore')})}}>Travel to {ATLAS_DESTINATIONS[Number(destination)].name}</button><button onClick={()=>void perform({type:'life',action:{kind:'waypoint',id:ATLAS_DESTINATIONS[Number(destination)].id}})}>Follow directions here</button><p>Discover new places by walking, riding or booking passage with an indoor village host.</p><p>{townPlots(ATLAS_DESTINATIONS[Number(destination)]).length} public buildings · gardens, lanes and surrounding farms</p><button disabled={busy} onClick={()=>void perform({type:'return-home'})}>Return to home marker</button><p className="shire-note">New atlas worlds use the pre-Scouring Shire. Original worlds retain their creative geography. Named locations are map-relative; household numbers and scenery are our reconstruction.</p></>:<><div className="shire-eyebrow">ROOM TO ROAM</div><h2>Your countryside</h2><LargeMap x={view.x} z={view.z} site={cinderlordSite(world)}/><p>Four kilometres across. The Shire settlements, roads and hill shapes here are designed layouts, not measured Tolkien map coordinates.</p>{SETTLEMENTS.map((s,i)=><button className="shire-destination" key={s.name} onClick={()=>void perform({type:'travel',settlement:i})}><span>{s.name}</span><small>{s.elves?'Fangorn · creative elven settlement':'Shire · inhabited neighbourhood'}</small></button>)}<button className="shire-destination" disabled={busy} onClick={()=>void perform({type:'travel-cinderlord'})}><span>Ashen Hollow · Cinderlord</span><small>Hostile magma guardian · travel to a safe overlook</small></button><button onClick={()=>void perform({type:'return-home'})}>Return to home marker</button><p className="shire-note">Walking also connects every area. Fangorn’s elves follow Al’s creative choice.</p></>)}
    {tab==='creatures'&&<CreatureJournal world={world} busy={busy} onAction={a=>{void perform(a).then(ok=>{if(ok)chooseTab('explore')})}} onRetry={()=>scene.current?.retryCreatureModels()}/>}
    {tab==='help'&&<><div className="shire-eyebrow">A FEW USEFUL THINGS</div><h2>Make a home</h2><ol><li>Walk to a hillside outside the public village and mark it as home.</li><li>Use Entry while aiming into a hill. Follow the descending tunnel into its level chamber.</li><li>Dig a Room deeper into the hill; connect more rooms with Passage.</li><li>Lower floors or raise ceilings, then add furniture. Keep a clear exit.</li><li>Plant outside, water and harvest. Feed and breed the farm animals.</li></ol><h3>Controls</h3><p>{['forward','left','back','right'].map(k=>keyLabel(world,k as 'forward'|'left'|'back'|'right')).join('/')} walk · {keyLabel(world,'run')} run · {keyLabel(world,'jump')} jump<br/>Right-drag look · LMB + RMB walk forward<br/>Right-click ground to walk there · Left-click selects<br/>Arrow keys turn/move<br/>Page Up/Down aim · {keyLabel(world,'apply')} apply · {keyLabel(world,'interact')} interact<br/>Esc pauses the world · change keys in Settings</p><h3>Combat & recovery</h3><p>{keyLabel(world,'apply')} or left click during captured mouse look strikes the aimed creature. {keyLabel(world,'guard')} raises a two-second guard: face the attacker. {keyLabel(world,'heal')} drinks a healing draught and cures burning or poison. {keyLabel(world,'dodge')} dodges the amber attack ring before impact. Equip your bow, sword or shield in Inventory; bows consume arrows. Attacks consume stamina; rest in a bed to heal and refill draughts. Fallen residents and animals recover after a delay. Defeated players recover at home.</p><h3>Backups & recovery</h3><button onClick={()=>void backup()}>Export backup to E:</button><button onClick={()=>void perform({type:'return-home'})}>Recover to home marker</button><p>Every accepted action is written to E:. Save & leave records your current position. A damaged save can be recovered into a separate slot from the welcome screen.</p><h3>Sources & asset boundaries</h3><p>The retained peoples workbook and atlas/races reports inform this project. Atlas geography is map-relative. Its elevations, local terrain shaping and building layouts are design interpretations. Exact source hashes and animal package provenance are retained beside local assets.</p><p className="shire-note">Hobbit residents and livestock use original Blender-authored game packages. The previously approved Grudge rabbit is retained with its provenance. The asset register distinguishes authored content from retained packages.</p></>}
    </aside>}
    {(message||error)&&<div className={`shire-toast ${error?'error':''}`} role={error?'alert':'status'}><span>{error||message}</span><button aria-label="Dismiss message" onClick={()=>{setMessage('');setError('')}}>×</button></div>}
    {!world.life?.paused&&<TouchControls input={(key,pressed)=>scene.current?.virtualInput(key,pressed)} interact={()=>scene.current?.interact()} apply={()=>scene.current?.applyTool()}/>}<div className="shire-sound-caption" aria-live="polite">{view.caption}</div>
    <nav className="shire-bottom" aria-label="World activities">{(['explore','journal','inventory','village','household','build','furnish','farm','animals','creatures','map','settings','help'] as Tab[]).map((t,i)=><button className={tab===t?'active':''} key={t} onClick={()=>chooseTab(t)}><span>{['⌂','✎','▣','♧','⌂','⌑','▤','❧','♧','⚔','◇','⚙','?'][i]}</span>{t[0].toUpperCase()+t.slice(1)}</button>)}<div className="shire-save-state">{view.pending?`Shaping ${view.pending} terrain pieces…`:`Saved revision ${world.revision}`}<small>{view.fps} fps · local on E:</small></div></nav>
  </main>
}
function MiniMap({x,z}:{x:number;z:number}){return <svg className="shire-minimap" viewBox="0 0 160 160" aria-label="Nearby landscape map"><rect width="160" height="160" fill="#c1c49b"/><path d="M0 28Q80 0 160 42M0 67Q80 38 160 75M0 113Q80 75 160 125" fill="none" stroke="#9fa573" strokeWidth="9"/><ellipse cx={80+(25-x)/3} cy={80+(114-z)/3} rx="7" ry="14" fill="#87a7a0"/>{SETTLEMENTS.map(s=><g key={s.name} transform={`translate(${80+(s.x-x)/3},${80+(s.z-z)/3})`}><circle r="7" fill="#9a7a52"/></g>)}<circle cx="80" cy="80" r="5" fill="#f3ead0" stroke="#354d38" strokeWidth="2"/><text x="80" y="14" textAnchor="middle" fill="#394c35" fontSize="10">N</text></svg>}
function LargeMap({x,z,site}:{x:number;z:number;site:{x:number;z:number}}){const map=(n:number)=>150+n/14;return <svg className="shire-large-map" viewBox="0 0 300 300" aria-label="Designed Shire and Fangorn map"><rect width="300" height="300" rx="10" fill="#bfc59b"/><path d="M12 45Q95 15 210 60M4 105Q150 55 300 135M0 215Q130 140 296 255" fill="none" stroke="#a0ad7c" strokeWidth="20"/><path d="M230 228Q285 205 299 290L299 299H218Z" fill="#516f4a"/>{SETTLEMENTS.slice(1).map(s=><line key={s.name} x1={map(55)} y1={map(30)} x2={map(s.x)} y2={map(s.z)} stroke="#e7dbab" strokeWidth="3"/>)}{SETTLEMENTS.map(s=><g key={s.name}><circle cx={map(s.x)} cy={map(s.z)} r="4" fill="#715633"/><text x={map(s.x)} y={map(s.z)-8} textAnchor="middle" fontSize="9" fill="#2f442d">{s.name}</text></g>)}<g><circle cx={map(site.x)} cy={map(site.z)} r="5" fill="#a13d22"/><text x={map(site.x)} y={map(site.z)-9} textAnchor="middle" fontSize="9" fill="#6e2819">Ashen Hollow</text></g><circle cx={map(x)} cy={map(z)} r="4" fill="#fff7db" stroke="#304d36" strokeWidth="2"/><text x="15" y="22" fill="#41513a" fontSize="11">N ↑</text><text x="15" y="286" fill="#41513a" fontSize="9">4 km · designed geography</text></svg>}

function nextObjective(w:World){
  const q=QUESTS.find(q=>w.life?.quests[q.id]?.state==='active'||w.life?.quests[q.id]?.state==='ready')
  if(!q)return 'Follow a lane, tend your home, or visit a neighbour.'
  if(w.life?.quests[q.id]?.state==='ready'){
    const host=w.life.residents.find(r=>r.role===q.role&&r.town===(isAtlas(w)?q.town:'legacy-0'))
    return `The work for “${q.name}” is done. Visit ${host?.name||'your neighbour'} and finish the request in your journal to receive its reward.`
  }
  return q.description
}
