import { WorkbenchLibrary } from './WorkbenchLibrary'
import { AtlasLandscape } from './AtlasLandscape'
import { WorldCombatView } from './WorldCombatView'
import { combatActor, living, combatBlocks, actorEnabled } from '@shared/shire/combat'
import { isAtlas, settlements, fallFloor, regionAt, nearestDestination, townPlots, TerrainContext, waterAt, ATLAS_BRIDGES, bridgeDeck } from '@shared/shire/atlas'
import * as T from 'three'
import { World, Tool, FurnitureKind, WorldAction, Point, SPECIES, SETTLEMENTS, FURNITURE, PLAYER_HEIGHT, FALL_RECOVERY_Y } from '@shared/shire/model'
import { clear, height, surfaceAt, rayTerrain, meshChunk, WATER_LEVEL } from '@shared/shire/terrain'
import { LoadManager } from '../LoadManager'
import { animalVisual, box, cropVisual, disposeObject, furnitureVisual, home, mat, palette, post, sign } from './visuals'
import { DEFAULT_TOOLS, ToolSettings, toolAction as plannedToolAction } from '@shared/shire/building'
import { BuildPreview } from './BuildPreview'
import { CinderlordEnemy } from './CinderlordEnemy'
import { CINDERLORD, cinderlordSite } from '@shared/shire/cinderlord'
import { LifeScene, type LifeTarget } from './LifeScene'
import { ShireAudio } from './ShireAudio'
import { DEFAULT_LIFE_SETTINGS, hourAt, PROFESSIONS } from '@shared/shire/lifeContent'
import type { InputAction } from '@shared/shire/lifeTypes'
import { navigationTarget } from '@shared/shire/navigation'
import { MouseTravelInput } from './MouseTravelInput'
import { RiderPose } from './RiderPose'
export type { ToolSettings } from '@shared/shire/building'

export interface ViewState { x:number;y:number;z:number;fps:number;pending:number;target:string;targetId?:string;targetKind?:'animal'|'crop'|'furniture'|'enemy'|'resident'|LifeTarget;region:string;locked:boolean;yaw?:number;caption?:string;preview?:string;enemy?:string }
type Chunk={mesh:T.Mesh;stamp:string}
import type {TerrainWork as Work,TerrainResult} from './terrainWork'

export class ShireScene {
  readonly scene=new T.Scene()
  readonly camera=new T.PerspectiveCamera(65,1,0.06,5500)
  readonly renderer:T.WebGLRenderer
  world:World
  settings:ToolSettings={...DEFAULT_TOOLS}
  player:World['player']
  private velocityY=0
  private keys=new Set<string>()
  private lastFrame=performance.now()
  private lifeView:LifeScene
  private audio:ShireAudio
  private caption=''
  private captionUntil=0
  private hemisphere!:T.HemisphereLight
  private avatar?:T.Object3D
  private avatarMixer?:T.AnimationMixer
  private avatarKey=''
  private avatarLoading=''
  private padPrevious:boolean[]=[]
  private padMove={forward:0,side:0,jump:false,run:false}
  private touchLook?:{id:number;x:number;y:number}
  private disposed=false
  private riderPose?:RiderPose
  private mouseTravel=new MouseTravelInput()
  private clickDestination?:Point
  private clickSerial=0
  private clickLast=new T.Vector3()
  private clickProgressAt=0
  private selectedId?:string
  private walkMarker=new T.Mesh(new T.RingGeometry(.28,.42,32),new T.MeshBasicMaterial({color:0xf9e9a8,side:T.DoubleSide,depthWrite:false}))
  private callbacks:{view:(state:ViewState)=>void;action:(a:WorldAction)=>void;message:(text:string)=>void;activity?:(tab:'inventory'|'village'|'household')=>void}
  private chunks=new Map<string,Chunk>()
  private workers:Worker[]=[]
  private idle:Worker[]=[]
  private queue:Work[]=[]
  private inflight=new Set<string>()
  private generation=0
  private editStamp=''
  private chunkAt=''
  private needed=new Set<string>()
  private terrainMaterial=new T.MeshStandardMaterial({vertexColors:true,roughness:1,side:T.FrontSide})
  private farCenter={value:new T.Vector2()}
  private atlasOrigin={value:new T.Vector2()}
  private objects=new Map<string,T.Object3D>()
  private objectSignatures=new Map<string,string>()
  private interactables:T.Object3D[]=[]
  private raycaster=new T.Raycaster()
  private target:ViewState['targetKind']|undefined
  private targetId:string|undefined
  private groundHit:ReturnType<typeof rayTerrain>=null
  private preview=new BuildPreview()
  private previewLabel=''
  private residents=new Map<string,{root:T.Object3D;mixer:T.AnimationMixer;origin:Point;phase:number}>()
  private residentsLoading=new Set<string>()
  private animalMixers=new Map<string,T.AnimationMixer>()
  private animalModels=new Set<string>()
  private animalLoading=new Set<string>()
  private availableAssets=new Map<string,string>()
  readonly workbench=new WorkbenchLibrary(this.scene)
  private combat:WorldCombatView
  private cinderlord?:CinderlordEnemy
  private atlas?:AtlasLandscape
  overview=false
  landmarkView=false
  private sun!:T.DirectionalLight
  private resizeObserver:ResizeObserver
  private viewTimer=0
  private frameTimes:number[]=[]
  private skyTime=0
  private loopHandle=0

  constructor(private container:HTMLElement,w:World,callbacks:ShireScene['callbacks']){
    this.world=w;this.player={...w.player};this.callbacks=callbacks
    if(isAtlas(w)){this.terrainMaterial.customProgramCacheKey=()=>'atlas-near';this.terrainMaterial.onBeforeCompile=shader=>{shader.uniforms.atlasPlayer=this.farCenter;shader.uniforms.atlasOrigin=this.atlasOrigin;shader.vertexShader='varying vec2 atlasNearXZ;uniform vec2 atlasOrigin;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\natlasNearXZ=(modelMatrix*vec4(position,1.0)).xz+atlasOrigin;');shader.fragmentShader='varying vec2 atlasNearXZ;uniform vec2 atlasPlayer;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <clipping_planes_fragment>','#include <clipping_planes_fragment>\nif(distance(atlasNearXZ,atlasPlayer)>118.0) discard;')}}
    this.renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=isAtlas(w)?0.87:1.05;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFShadowMap
    this.scene.background=new T.Color(0xbaccc3);this.scene.fog=new T.FogExp2(0xbaccc3,0.0007)
    this.hemisphere=new T.HemisphereLight(0xe3e8da,0x6b6c48,isAtlas(w)?1.7:2.6);this.scene.add(this.hemisphere);const sun=new T.DirectionalLight(0xffedcf,isAtlas(w)?2.2:2.8);this.sun=sun;sun.position.set(-60,110,50);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-95;sun.shadow.camera.right=95;sun.shadow.camera.top=95;sun.shadow.camera.bottom=-95;sun.shadow.bias=-0.001;this.scene.add(sun,sun.target)
    const carried=new T.PointLight(0xffd9a4,2.2,16,1.5);this.camera.add(carried);this.scene.add(this.camera)
    this.walkMarker.rotation.x=-Math.PI/2;this.walkMarker.visible=false;this.scene.add(this.walkMarker);this.preview.visible=false;this.scene.add(this.preview);this.container.appendChild(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','The Middle-earth game view');this.renderer.domElement.tabIndex=0
    this.resizeObserver=new ResizeObserver(this.resize);this.resizeObserver.observe(container);this.resize()
    for(let i=0;i<2;i++){const worker=new Worker(new URL('./terrain.worker.ts',import.meta.url));worker.onmessage=event=>this.receiveChunk(worker,event.data);worker.onerror=()=>this.callbacks.message('A terrain worker failed. Save and reopen the world to recover.');this.workers.push(worker);this.idle.push(worker)}
    this.combat=new WorldCombatView(this.scene,text=>this.callbacks.message(text));this.lifeView=new LifeScene(this.scene);this.audio=new ShireAudio(text=>{this.caption=text;this.captionUntil=this.skyTime+4})
    if(isAtlas(w)){this.atlas=new AtlasLandscape(this.scene,w,text=>this.callbacks.message(text));this.atlas.update(this.player)}else{this.makeLandscape();this.makeSettlements()}this.setWorld(w,true)
    window.addEventListener('keydown',this.keyDown);window.addEventListener('keyup',this.keyUp);window.addEventListener('blur',this.releaseInput);document.addEventListener('pointerlockchange',this.lockChange);document.addEventListener('mousemove',this.mouseMove);document.addEventListener('mouseup',this.mouseUp);this.renderer.domElement.tabIndex=0;this.renderer.domElement.addEventListener('mousedown',this.mouseDown);this.renderer.domElement.addEventListener('contextmenu',this.contextMenu)
    void fetch('/api/shire/assets').then(r=>r.json()).then(data=>{if(this.disposed)return;for(const a of data.assets||[])this.availableAssets.set(a.id,a.url);this.loadAnimalModels()}).catch(()=>{})
    this.renderer.domElement.addEventListener('pointerdown',this.touchDown);this.renderer.domElement.addEventListener('pointermove',this.touchMove);this.renderer.domElement.addEventListener('pointerup',this.touchUp);this.renderer.domElement.addEventListener('pointercancel',this.touchUp)
    this.loop()
  }
  private resize=()=>{const width=this.container.clientWidth,height=this.container.clientHeight;this.renderer.setSize(width,height);this.camera.aspect=width/Math.max(1,height);this.camera.updateProjectionMatrix()}
  private contextMenu=(e:Event)=>e.preventDefault()
  private binding(action:InputAction){return (this.world.life?.settings||DEFAULT_LIFE_SETTINGS).bindings[action]}
  virtualInput(action:InputAction,pressed:boolean){const code=this.binding(action);if(pressed)this.keys.add(code);else this.keys.delete(code)}
  private keyDown=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,textarea,select')&&e.code!=='Escape')return;if((e.target as HTMLElement)?.closest('button')&&['Space','Enter'].includes(e.code))return;if(Object.values((this.world.life?.settings||DEFAULT_LIFE_SETTINGS).bindings).includes(e.code))e.preventDefault();if(e.code==='Escape'&&!e.repeat){this.releaseInput();this.callbacks.action({type:'life',action:{kind:'pause',value:!this.world.life?.paused}});return}if(this.world.life?.paused)return;if(['forward','back','left','right','jump','dive'].some(k=>e.code===this.binding(k as InputAction))||['ArrowLeft','ArrowRight'].includes(e.code))this.cancelClickTravel();this.keys.add(e.code);if(e.repeat)return;if(e.code===this.binding('interact'))this.interact();if(e.code===this.binding('apply'))this.settings.tool==='explore'?this.strike():this.applyTool();if(e.code===this.binding('guard'))this.callbacks.action({type:'guard'});if(e.code===this.binding('heal'))this.callbacks.action({type:'heal'});if(e.code===this.binding('dodge'))this.callbacks.action({type:'life',action:{kind:'dodge'}})}
  private touchDown=(e:PointerEvent)=>{if(e.pointerType!=='touch'||this.world.life?.paused)return;this.touchLook={id:e.pointerId,x:e.clientX,y:e.clientY};this.renderer.domElement.setPointerCapture(e.pointerId)}
  private touchMove=(e:PointerEvent)=>{if(!this.touchLook||this.touchLook.id!==e.pointerId)return;const sensitivity=(this.world.life?.settings.sensitivity||1)*.006;this.player.yaw-=(e.clientX-this.touchLook.x)*sensitivity;this.player.pitch=T.MathUtils.clamp(this.player.pitch-(e.clientY-this.touchLook.y)*sensitivity*(this.world.life?.settings.invertY?-1:1),-1.4,1.4);this.touchLook.x=e.clientX;this.touchLook.y=e.clientY}
  private touchUp=(e:PointerEvent)=>{if(this.touchLook?.id===e.pointerId)this.touchLook=undefined}
  private gamepad(dt:number){const p=navigator.getGamepads?.().find(p=>p?.mapping==='standard');if(!p){this.padMove={forward:0,side:0,jump:false,run:false};return}const axis=(n:number)=>Math.abs(n)>.18?n:0;this.padMove={forward:-axis(p.axes[1]),side:axis(p.axes[0]),jump:p.buttons[0].pressed,run:p.buttons[10].pressed};if(!this.world.life?.paused){const sens=this.world.life?.settings.sensitivity||1;this.player.yaw-=axis(p.axes[2])*dt*2.2*sens;this.player.pitch=T.MathUtils.clamp(this.player.pitch-axis(p.axes[3])*dt*1.7*sens*(this.world.life?.settings.invertY?-1:1),-1.4,1.4)}for(const [i,button]of p.buttons.entries()){if(button.pressed&&!this.padPrevious[i]){if(i===9){this.releaseInput();this.callbacks.action({type:'life',action:{kind:'pause',value:!this.world.life?.paused}})}else if(!this.world.life?.paused){if(i===2)this.interact();if(i===7)this.settings.tool==='explore'?this.strike():this.applyTool();if(i===6)this.guard();if(i===1)this.callbacks.action({type:'life',action:{kind:'dodge'}})}}this.padPrevious[i]=button.pressed}}
  private keyUp=(e:KeyboardEvent)=>this.keys.delete(e.code)
  private pointerRay(e:MouseEvent){const rect=this.renderer.domElement.getBoundingClientRect();this.camera.updateMatrixWorld();this.raycaster.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),this.camera);this.raycaster.far=180;return this.raycaster.ray}
  private cancelClickTravel(){this.clickDestination=undefined;this.walkMarker.visible=false}
  private selectAt(e:MouseEvent){
    this.pointerRay(e);this.refreshInteractables();const hit=this.raycaster.intersectObjects(this.interactables,true)[0];let root:T.Object3D|undefined=hit?.object;while(root&&!root.userData.id)root=root.parent||undefined
    this.selectedId=root?.userData.id;this.cancelClickTravel();if(root)this.callbacks.message('Selected '+root.userData.label+'. Use your interaction or strike control when within reach.')
  }
  private walkToPointer(e:MouseEvent){
    this.cancelClickTravel();this.selectedId=undefined;if(this.settings.tool!=='explore'||this.world.life?.settings.clickToMove===false||this.world.life?.transport||this.world.life?.seated||this.overview)return
    const ray=this.pointerRay(e).clone();ray.origin.sub(this.scene.position);let hit=rayTerrain(ray.origin,ray.direction,this.world,180)
    if(isAtlas(this.world)&&Math.abs(ray.direction.y)>.0001)for(const b of ATLAS_BRIDGES){const t=(bridgeDeck(b)-ray.origin.y)/ray.direction.y;if(t<=0||t>180||hit&&hit.distance<t)continue;const x=ray.origin.x+ray.direction.x*t,z=ray.origin.z+ray.direction.z*t;if(Math.abs(b.turn?x-b.x:z-b.z)<b.width/2-.35&&Math.abs(b.turn?z-b.z:x-b.x)<b.length/2)hit={x,y:bridgeDeck(b),z,distance:t}}
    if(!hit){this.callbacks.message('Right-click a nearby patch of ground to walk there.');return}
    const point={x:hit.x,y:surfaceAt(hit.x,hit.z,this.world,hit.y+.2)+.08,z:hit.z}
    if(Math.hypot(point.x-this.player.x,point.z-this.player.z)>185||!clear(point,this.world)||!this.world.life?.interior&&point.y<=waterAt(point.x,point.z,this.world)+.1){this.callbacks.message('Choose dry, open ground for a walking destination.');return}
    this.clickDestination=point;this.clickSerial++;this.clickLast.set(this.player.x,this.player.y,this.player.z);this.clickProgressAt=this.skyTime;this.walkMarker.position.set(point.x,point.y+.03,point.z);this.walkMarker.visible=true
  }
  private mouseDown=(e:MouseEvent)=>{this.renderer.domElement.focus({preventScroll:true});if(this.world.life?.paused)return;this.mouseTravel.press(e.button,e.buttons);if(e.button===2||this.mouseTravel.forward)this.cancelClickTravel()}
  private mouseUp=(e:MouseEvent)=>{const action=this.mouseTravel.release(e.button);if(this.world.life?.paused)return;if(action==='point'&&document.pointerLockElement!==this.renderer.domElement)this.walkToPointer(e);if(action==='primary'){if(document.pointerLockElement===this.renderer.domElement)this.settings.tool==='explore'?this.strike():this.applyTool();else if(this.settings.tool==='explore')this.selectAt(e)}}
  private mouseMove=(e:MouseEvent)=>{this.mouseTravel.motion(e.movementX,e.movementY);if(this.mouseTravel.right||document.pointerLockElement===this.renderer.domElement){const sens=(this.world.life?.settings.sensitivity||1)*.0022;this.player.yaw-=e.movementX*sens;this.player.pitch=Math.max(-1.4,Math.min(1.4,this.player.pitch-e.movementY*sens*(this.world.life?.settings.invertY?-1:1)))}}
  private lockChange=()=>{this.mouseTravel.reset();this.cancelClickTravel();if(document.pointerLockElement!==this.renderer.domElement)this.keys.clear()}
  capture=()=>{if(this.world.life?.paused){this.callbacks.action({type:'life',action:{kind:'pause',value:false}});return}this.renderer.domElement.focus();void this.renderer.domElement.requestPointerLock()?.catch(()=>this.callbacks.message('Use right-drag to look and WASD to walk.'))}
  releaseInput=()=>{this.keys.clear();this.touchLook=undefined;this.mouseTravel.reset();this.cancelClickTravel();this.selectedId=undefined;if(document.pointerLockElement===this.renderer.domElement)document.exitPointerLock()}
  setSettings(settings:ToolSettings){this.settings=settings;if(settings.tool!=='explore')this.releaseInput()}
  getPlayer(){return {...this.player}}
  getCombatDiagnostics(){return this.combat.diagnostics}
  getPerformanceDiagnostics(){const times=this.frameTimes.map(t=>t*1000).sort((a,b)=>a-b);return {frames:times.length,p50:times[Math.floor(times.length*.5)],p95:times[Math.floor(times.length*.95)],max:times.at(-1),terrain:{loaded:this.chunks.size,queued:this.queue.length,inflight:this.inflight.size},renderer:{...this.renderer.info.memory,drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles},animalModels:[...this.animalModels],animalClips:[...this.objects].filter(([,o])=>o.userData.kind==='animal').map(([id,o])=>({id,clip:o.userData.clip,position:o.position.toArray()})),residentModels:this.residents.size}}
  faceWaypoint(){const p=this.world.life?.waypoint?.position;if(!p||this.world.life?.interior)return;this.releaseInput();this.player.yaw=Math.atan2(this.player.x-p.x,this.player.z-p.z);this.player.pitch=-.08}
  private qaUntil=0
  qaWalk(seconds:number,backward=false){if(!new URLSearchParams(location.search).has('combatQA'))return;this.releaseInput();this.keys.add(this.binding(backward?'back':'forward'));this.qaUntil=this.skyTime+Math.min(8,Math.max(0,seconds))}
  qaFace(kind='hostile'){if(!new URLSearchParams(location.search).has('combatQA'))return;const nearest=this.world.combat?.actors.filter(a=>a.kind===kind).sort((a,b)=>Math.hypot(a.position.x-this.player.x,a.position.z-this.player.z)-Math.hypot(b.position.x-this.player.x,b.position.z-this.player.z))[0];if(nearest){const dx=this.player.x-nearest.position.x,dz=this.player.z-nearest.position.z;this.player.yaw=Math.atan2(dx,dz);this.player.pitch=Math.atan2(nearest.position.y+(kind==='animal'?.35:.9)-this.player.y-PLAYER_HEIGHT+.08,Math.hypot(dx,dz))}}
  qaDive(){if(!new URLSearchParams(location.search).has('combatQA'))return;this.releaseInput();this.keys.add('ControlLeft');this.qaUntil=this.skyTime+6}
  retryCreatureModels(){this.combat.retry()}
  strike(){if(this.world.life?.style==='homestead'){this.interact();return}if(this.targetId&&['enemy','animal','resident'].includes(this.target||''))this.callbacks.action({type:'strike',id:this.targetId});else this.callbacks.message('Aim at a living creature within reach to strike.')}
  guard(){this.callbacks.action({type:'guard'})}
  furnishAhead(){const x=this.player.x-Math.sin(this.player.yaw)*2.7,z=this.player.z-Math.cos(this.player.yaw)*2.7;this.callbacks.action({type:'furnish',kind:this.settings.furniture,position:{x,y:surfaceAt(x,z,this.world,this.player.y+1),z},yaw:this.settings.yaw})}
  claim(){const hit=this.groundHit;this.callbacks.action({type:'claim',position:hit?{x:hit.x,y:hit.y,z:hit.z}:{...this.player}})}
  private geometry(mesh:{positions:Float32Array;normals:Float32Array;colors:Float32Array}){const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(mesh.positions,3));geometry.setAttribute('normal',new T.BufferAttribute(mesh.normals,3));geometry.setAttribute('color',new T.BufferAttribute(mesh.colors,3));geometry.computeBoundingSphere();return geometry}
  private receiveChunk(worker:Worker,data:TerrainResult){
    if(this.disposed)return;this.inflight.delete(`${data.key}:${data.revision}`);this.idle.push(worker)
    if(data.revision===this.generation&&this.needed.has(data.key)&&'positions' in data){const old=this.chunks.get(data.key);if(old){this.scene.remove(old.mesh);old.mesh.geometry.dispose()}const mesh=new T.Mesh(this.geometry(data),this.terrainMaterial);mesh.receiveShadow=true;mesh.castShadow=true;this.scene.add(mesh);this.chunks.set(data.key,{mesh,stamp:data.stamp})}
    if(data.error)this.callbacks.message(data.error);this.pump()
  }
  private pump(){while(this.idle.length&&this.queue.length){const task=this.queue.shift()!;if(task.revision!==this.generation||!this.needed.has(task.key))continue;const worker=this.idle.pop()!;this.inflight.add(`${task.key}:${task.revision}`);worker.postMessage(task)}}
  private terrain(force=false){if(this.world.life?.interior)return;const cx=Math.floor(this.player.x/16),cz=Math.floor(this.player.z/16),at=`${cx}:${cz}`;if(at===this.chunkAt&&!force)return;this.chunkAt=at;this.farCenter.value.set(this.player.x,this.player.z);const needed=new Set<string>();const jobs:Work[]=[]
    for(let dx=-9;dx<=9;dx++)for(let dz=-9;dz<=9;dz++){if(Math.hypot(dx,dz)>9.6)continue;const x=cx+dx,z=cz+dz,key=`${x}:${z}`;needed.add(key);const old=this.chunks.get(key)
      const nearEdits=this.world.edits.filter(e=>Math.abs(e.center.x-(x*16+8))<Math.hypot(e.size.x,e.size.z)+10&&Math.abs(e.center.z-(z*16+8))<Math.hypot(e.size.x,e.size.z)+10)
      if(old?.stamp===nearEdits.map(e=>e.id).join(':'))continue
      if(!this.inflight.has(`${key}:${this.generation}`)&&!this.queue.some(j=>j.key===key&&j.revision===this.generation))jobs.push({key,cx:x,cz:z,seed:{seed:this.world.seed,generator:this.world.generator},edits:nearEdits,revision:this.generation})
    }
    this.needed=needed;this.queue=this.queue.filter(j=>needed.has(j.key)&&j.revision===this.generation);jobs.sort((a,b)=>Math.hypot(a.cx-cx,a.cz-cz)-Math.hypot(b.cx-cx,b.cz-cz));this.queue.push(...jobs)
    for(const [key,chunk] of this.chunks)if(!needed.has(key)){this.scene.remove(chunk.mesh);chunk.mesh.geometry.dispose();this.chunks.delete(key)}this.pump()
  }
  setWorld(w:World,move=false){const previous=this.world;this.world=w;if(previous.life?.interior?.id!==w.life?.interior?.id)move=true;if(w.life?.transport||previous.life?.transport){this.player={...this.player,x:w.player.x,y:w.player.y,z:w.player.z};if(previous.life?.transport&&!w.life?.transport&&(w.life?.stats.ferryTrips||0)>(previous.life?.stats.ferryTrips||0))this.callbacks.message('The ferry has docked. You can step ashore.');}if(w.life?.paused)this.releaseInput();const comfort=w.life?.settings;if(comfort){if(this.camera.fov!==comfort.fov){this.camera.fov=comfort.fov;this.camera.updateProjectionMatrix()}this.renderer.setPixelRatio(Math.min(window.devicePixelRatio,comfort.quality==='low'?1:comfort.quality==='medium'?1.25:1.5));this.renderer.shadowMap.enabled=comfort.quality!=='low'}if(combatActor(w,'player')?.vitality.hp===0){this.releaseInput();this.velocityY=0;this.player={...w.player}}if(move){this.releaseInput();this.player={...w.player};this.velocityY=0;this.chunkAt='';this.terrain(true);this.atlas?.update(this.player)}const stamp=w.edits.map(e=>e.id).join(':');if(stamp!==this.editStamp||this.chunks.size===0&&!this.queue.length&&!this.inflight.size){this.editStamp=stamp;this.generation++;this.terrain(true)}
    const keep=new Set<string>()
    for(const f of w.furniture){if(w.life?.interior||Math.hypot(f.position.x-this.player.x,f.position.z-this.player.z)>180)continue;keep.add(f.id);const signature=JSON.stringify(f);if(this.objectSignatures.get(f.id)!==signature){this.removeObject(f.id);const obj=furnitureVisual(f);obj.position.set(f.position.x,f.position.y,f.position.z);obj.rotation.y=f.yaw;obj.userData={kind:'furniture',id:f.id,label:FURNITURE[f.kind].label+(f.kind==='feeder'?` · ${f.stock||0}/12 feed`:f.kind==='perch'||f.kind==='burrow'?f.open?' · open':' · closed':'')};this.addObject(f.id,obj,signature)}}
    for(const crop of w.crops){if(crop.harvested||w.life?.interior||Math.hypot(crop.position.x-this.player.x,crop.position.z-this.player.z)>180)continue;keep.add(crop.id);const progress=crop.watered?Math.min(1,(w.time-crop.planted)/60):0,stage=Math.floor(progress*5),signature=`${stage}:${crop.watered}`;if(this.objectSignatures.get(crop.id)!==signature){this.removeObject(crop.id);const obj=cropVisual(crop.kind,stage/5,crop.watered);obj.position.set(crop.position.x,crop.position.y,crop.position.z);obj.userData={kind:'crop',id:crop.id,label:`${crop.kind} · ${!crop.watered?'needs water':progress>=1?'ready to harvest':'growing'}`};this.addObject(crop.id,obj,signature)}}
    for(const animal of w.animals){if(w.life?.interior||Math.hypot(animal.position.x-this.player.x,animal.position.z-this.player.z)>160)continue;keep.add(animal.id);let obj=this.objects.get(animal.id);if(!obj){obj=animalVisual(animal);obj.position.set(animal.position.x,animal.position.y,animal.position.z);obj.userData={...obj.userData,kind:'animal',id:animal.id,label:animal.name};this.addObject(animal.id,obj,animal.species)}obj.userData.label=`${animal.name}${animal.age<SPECIES[animal.species].maturity?' · young':''}${animal.pregnant?' · expecting young':''} · ${animal.activity||animal.mood}`;obj.scale.setScalar((this.animalModels.has(animal.id)?1:SPECIES[animal.species].scale)*(animal.age<SPECIES[animal.species].maturity?0.55:1))}
    for(const key of this.objects.keys())if(!keep.has(key))this.removeObject(key);this.refreshInteractables();this.loadAnimalModels()
  }
  private refreshInteractables(){this.interactables=[...this.objects.values()].filter(o=>o.visible).concat(this.combat.roots.filter(o=>o.visible),[...[...this.residents.values()].map(r=>r.root)].filter(o=>o.visible),this.lifeView?.interactables||[])}
  private addObject(id:string,obj:T.Object3D,signature:string){this.objects.set(id,obj);this.objectSignatures.set(id,signature);this.scene.add(obj)}
  private removeObject(id:string){const obj=this.objects.get(id);if(obj){this.scene.remove(obj);if(this.animalModels.has(id)){LoadManager.releaseClone(obj);this.animalModels.delete(id);this.animalMixers.delete(id)}else disposeObject(obj);this.objects.delete(id);this.objectSignatures.delete(id)}}
  private makeLandscape(){
    const far=new T.PlaneGeometry(4200,4200,210,210);far.rotateX(-Math.PI/2);const p=far.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,height(p.getX(i),p.getZ(i),this.world));far.computeVertexNormals();const fm=new T.MeshStandardMaterial({color:0x657c3b,roughness:1});fm.onBeforeCompile=shader=>{shader.uniforms.shireCenter=this.farCenter;shader.vertexShader='varying vec2 shireXZ;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nshireXZ = position.xz;');shader.fragmentShader='varying vec2 shireXZ; uniform vec2 shireCenter;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <clipping_planes_fragment>','#include <clipping_planes_fragment>\nif(distance(shireXZ,shireCenter)<118.0) discard;')};const ground=new T.Mesh(far,fm);ground.receiveShadow=true;this.scene.add(ground)
    const pond=new T.Mesh(new T.CircleGeometry(1,64),new T.MeshStandardMaterial({color:0x769c9b,roughness:0.2,metalness:0.2,transparent:true,opacity:0.83}));pond.rotation.x=-Math.PI/2;pond.scale.set(14,28,1);pond.position.set(25,WATER_LEVEL,114);this.scene.add(pond)
    let seed=this.world.seed;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)|0;return(seed>>>0)/4294967296};const matrix=new T.Matrix4(),q=new T.Quaternion(),scale=new T.Vector3(),position=new T.Vector3()
    const encounter=cinderlordSite(this.world)
    const trees=1100,trunks=new T.InstancedMesh(new T.CylinderGeometry(0.3,0.48,5,5),mat(0x675541),trees),crowns=new T.InstancedMesh(new T.SphereGeometry(1,7,5),mat(0x46683b),trees)
    let used=0;for(let i=0;i<trees;i++){const forest=i<650,x=forest?1050+rand()*900:(rand()-0.5)*3000,z=forest?1050+rand()*900:(rand()-0.5)*3000;if(Math.hypot(x-encounter.x,z-encounter.z)<34||SETTLEMENTS.some(s=>Math.hypot(s.x-x,s.z-z)<48)||height(x,z,this.world)<WATER_LEVEL||Math.hypot(x+30,z)<38)continue;const h=0.6+rand()*0.9;position.set(x,height(x,z,this.world)+h*2.5,z);scale.set(h,h,h);matrix.compose(position,q,scale);trunks.setMatrixAt(used,matrix);position.y+=h*2.7;scale.set(h*3.5,h*3.7,h*3.3);matrix.compose(position,q,scale);crowns.setMatrixAt(used,matrix);used++}trunks.count=used;crowns.count=used;trunks.castShadow=true;crowns.castShadow=true;this.scene.add(trunks,crowns)
    const flowers=new T.InstancedMesh(new T.ConeGeometry(0.12,0.4,3),mat(0xd6c394),1800);for(let i=0;i<1800;i++){const x=(rand()-0.5)*350,z=(rand()-0.5)*350;position.set(x,height(x,z,this.world)+0.16,z);scale.setScalar(0.6+rand()*0.6);matrix.compose(position,q,scale);flowers.setMatrixAt(i,matrix)}this.scene.add(flowers)
    for(const destination of SETTLEMENTS.slice(1)){const start=SETTLEMENTS[0],length=Math.hypot(destination.x-start.x,destination.z-start.z),segments=Math.ceil(length/6),verts:number[]=[];for(let i=0;i<segments;i++){const t=i/segments,u=(i+1)/segments,dx=(destination.x-start.x)/length,dz=(destination.z-start.z)/length;for(const [a,side] of [[t,-1],[u,-1],[u,1],[t,-1],[u,1],[t,1]]){const x=start.x+(destination.x-start.x)*a+dz*side*1.4,z=start.z+(destination.z-start.z)*a-dx*side*1.4;verts.push(x,height(x,z,this.world)+0.05,z)}}const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(verts,3));geometry.computeVertexNormals();const path=new T.Mesh(geometry,new T.MeshStandardMaterial({color:0xb6a582,roughness:1,side:T.DoubleSide}));this.scene.add(path)}
  }
  private makeSettlements(){for(const [j,s]of settlements(this.world).entries()){for(let i=0;i<s.homes;i++){const angle=i/s.homes*Math.PI*2,r=13+(i%3)*6,x=s.x+Math.sin(angle)*r,z=s.z+Math.cos(angle)*r;const house=home([0x65754a,0x637a87,0x995f48,0x8b784a][i%4]);house.position.set(x,height(x,z,this.world),z);house.rotation.y=angle+Math.PI;this.scene.add(house)}const board=sign(s.elves?'FANGORN\nElven clearing':`${s.name.toUpperCase()}\nTHE SHIRE`,5);board.position.set(s.x-28,height(s.x-28,s.z,this.world)+2.6,s.z);board.rotation.y=Math.PI/2;this.scene.add(board);post(this.scene,s.x-28,board.position.y-1.3,s.z,0.12,2.6,palette.wood)}
    const board=sign('A HILL TO CALL HOME\nChoose a hill beyond the village',5);board.position.set(-48,height(-48,20,this.world)+2.3,20);board.rotation.y=-Math.PI/3;this.scene.add(board)
    const farm=sign('MILLBROOK FARM\nWater · feed · raise young',4);farm.position.set(3,height(3,43,this.world)+2,43);this.scene.add(farm)
  }
  private loadResidents(){if(this.world.life?.interior)return;for(const [key,r]of this.residents){if(Math.hypot(r.origin.x-this.player.x,r.origin.z-this.player.z)>700){r.mixer.stopAllAction();LoadManager.releaseClone(r.root.children[0]);this.scene.remove(r.root);this.residents.delete(key)}}for(const [j,s]of settlements(this.world).entries()){if(Math.hypot(s.x-this.player.x,s.z-this.player.z)>220)continue;for(let i=0;i<Math.min(6,s.homes);i++){const key=`${j}:${i}`;if(this.residents.has(key)||this.residentsLoading.has(key))continue;this.residentsLoading.add(key);const npc=this.world.life?.residents.find(r=>r.id==='resident:'+key),asset=s.elves?'resident-elf':isAtlas(this.world)&&['Bree','Staddle','Combe','Archet'].includes(s.name)?'resident-human':npc?.female?'resident-hobbit-female':'resident-hobbit-male',url=this.availableAssets.get(asset);if(!url){this.residentsLoading.delete(key);continue}void LoadManager.glTFLoad(url).then(root=>{if(this.disposed||Math.hypot(s.x-this.player.x,s.z-this.player.z)>700){LoadManager.releaseClone(root);return}const bounds=new T.Box3().setFromObject(root),height0=bounds.max.y-bounds.min.y,target=s.elves?1.75:isAtlas(this.world)&&['Bree','Combe','Archet'].includes(s.name)?1.7:1.1;root.scale.setScalar(target/(height0||1));const actor=new T.Group();root.position.y=-bounds.min.y*root.scale.y;actor.add(root);const origin={x:s.x+Math.sin(i)*8+12,y:0,z:s.z+Math.cos(i)*8+(s.name==='Hobbiton'?-40:4)};origin.y=height(origin.x,origin.z,this.world);actor.position.set(origin.x,origin.y,origin.z);this.scene.add(actor);const mixer=new T.AnimationMixer(root),clip=root.animations.find(c=>/walk/i.test(c.name))||root.animations[0];if(clip)mixer.clipAction(clip).play();actor.userData={id:`resident:${key}`,kind:'resident',label:`${s.name} resident ${i+1}`};this.residents.set(key,{root:actor,mixer,origin,phase:i})}).catch(()=>this.callbacks.message('A resident model could not load. Check the local asset package.')).finally(()=>this.residentsLoading.delete(key))}}}
  private loadAnimalModels(){for(const a of this.world.animals){const url=this.availableAssets.get(`animal-${a.species}`);if(!this.objects.has(a.id)||!url||this.animalModels.has(a.id)||this.animalLoading.has(a.id))continue;this.animalLoading.add(a.id);void LoadManager.glTFLoad(url).then(root=>{if(this.disposed){LoadManager.releaseClone(root);return}const existing=this.objects.get(a.id);if(!existing){LoadManager.releaseClone(root);return}const bounds=new T.Box3().setFromObject(root),size=bounds.getSize(new T.Vector3()),scale=a.species==='rabbit'?0.65/Math.max(size.x,size.y,size.z,0.001):1;root.scale.setScalar(scale);root.position.set(-(bounds.min.x+bounds.max.x)*scale/2,-bounds.min.y*scale,-(bounds.min.z+bounds.max.z)*scale/2);const mount=new T.Group();mount.add(root);mount.scale.setScalar(a.age<SPECIES[a.species].maturity?0.55:1);mount.position.copy(existing.position);mount.userData={kind:'animal',id:a.id,label:a.name,developmentVisual:false};this.removeObject(a.id);this.addObject(a.id,mount,a.species);this.animalModels.add(a.id);const mixer=new T.AnimationMixer(root);const idle=root.animations.find(c=>c.name==='idle')||root.animations[0];if(idle)mixer.clipAction(idle).play();this.animalMixers.set(a.id,mixer);this.refreshInteractables()}).catch(()=>this.callbacks.message(`The ${a.species} package could not load. Check its entry in the local asset register.`)).finally(()=>this.animalLoading.delete(a.id))}}
  private updateTarget(){this.refreshInteractables();this.camera.updateMatrixWorld();const direction=new T.Vector3();this.camera.getWorldDirection(direction);this.groundHit=rayTerrain(this.camera.position,direction,this.world,10);this.raycaster.setFromCamera(new T.Vector2(0,0),this.camera);this.raycaster.far=this.world.life?.equipment.weapon==='bow'?35:9;for(const root of this.interactables){if(Math.hypot(root.position.x-this.player.x,root.position.z-this.player.z)>40)continue;root.traverse(o=>{if(o instanceof T.SkinnedMesh){o.computeBoundingSphere();if(o.boundingBox)o.computeBoundingBox()}})}const hit=this.raycaster.intersectObjects(this.interactables,true)[0];this.target=undefined;this.targetId=undefined;let label=this.groundHit?'Earth':'';if(hit&&(!this.groundHit||hit.distance<this.groundHit.distance+0.1)){let obj:T.Object3D|null=hit.object;while(obj&&!obj.userData.id)obj=obj.parent;if(obj){this.target=obj.userData.kind;this.targetId=obj.userData.id;label=obj.userData.label}}
    if(this.selectedId&&this.settings.tool==='explore'){const selected=this.interactables.find(o=>o.userData.id===this.selectedId);if(selected&&Math.hypot(selected.position.x-this.player.x,selected.position.z-this.player.z)<40){this.target=selected.userData.kind;this.targetId=selected.userData.id;label=selected.userData.label}else this.selectedId=undefined}
    this.previewLabel=this.preview.update(this.settings.tool==='explore'?null:this.toolAction(),this.world)
    return label
  }
  private toolAction():WorldAction|null{const direction=new T.Vector3();this.camera.getWorldDirection(direction);return plannedToolAction(this.settings,this.groundHit,this.player,direction)}
  applyTool(){if(this.settings.tool==='explore'){this.interact();return}const action=this.toolAction();if(action)this.callbacks.action(action);else this.callbacks.message('Look at nearby earth or a floor, then apply the tool.')}
  interact(){if(this.world.life?.paused)return;if(this.target==='enemy'){this.strike();return}if(this.target==='resident'&&this.targetId){this.callbacks.action({type:'life',action:{kind:'talk',id:this.targetId}});return}if(this.target&&this.targetId&&['entrance','resource','room-service','special-crop','ferry','rune','gate','landmark'].includes(this.target)){if(this.target==='room-service'&&['hearth','bench','millstone','anvil'].includes(this.targetId)){this.callbacks.activity?.('inventory');return}this.callbacks.action(this.lifeView.action(this.target as LifeTarget,this.targetId));return}if(this.target==='furniture'&&this.targetId){const f=this.world.furniture.find(f=>f.id===this.targetId);if(f?.kind==='chest')this.callbacks.activity?.('household');if(f?.kind==='chair'){this.callbacks.action({type:'life',action:{kind:'sit',id:f.id}});return}this.callbacks.action({type:'use-furniture',id:this.targetId})}else if(this.target==='crop'&&this.targetId){const c=this.world.crops.find(c=>c.id===this.targetId)!;this.callbacks.action({type:!c.watered?'water':'harvest',id:c.id})}else if(this.target==='animal'&&this.targetId)this.callbacks.action({type:'feed',id:this.targetId});else this.callbacks.message('Look at a door, neighbour, resource, animal or household object to interact.')}

  private move(dt:number){if(this.overview||this.world.life?.paused||this.world.life?.transport||this.world.life?.seated||combatActor(this.world,'player')?.vitality.hp===0)return;if(!this.world.life?.interior&&!this.chunks.has(Math.floor(this.player.x/16)+':'+Math.floor(this.player.z/16)))return
    if(this.keys.has('ArrowLeft'))this.player.yaw+=dt*1.5;if(this.keys.has('ArrowRight'))this.player.yaw-=dt*1.5;if(this.keys.has('PageUp'))this.player.pitch=Math.min(1.4,this.player.pitch+dt);if(this.keys.has('PageDown'))this.player.pitch=Math.max(-1.4,this.player.pitch-dt)
    const water=waterAt(this.player.x,this.player.z,this.world),swimming=!this.world.life?.interior&&this.player.y<water-.65
    let forward=T.MathUtils.clamp(Number(this.keys.has(this.binding('forward')))-Number(this.keys.has(this.binding('back')))+this.padMove.forward+Number(this.mouseTravel.forward),-1,1);const side=T.MathUtils.clamp(Number(this.keys.has(this.binding('right')))-Number(this.keys.has(this.binding('left')))+this.padMove.side,-1,1)
    if(forward||side)this.cancelClickTravel()
    if(this.clickDestination){
      const destination=this.clickDestination,remaining=Math.hypot(destination.x-this.player.x,destination.z-this.player.z)
      if(remaining<.85)this.cancelClickTravel()
      else{const next=navigationTarget(this.world,'mouse-travel:'+this.clickSerial,this.player,destination);if(!next){this.cancelClickTravel();this.callbacks.message('Choose another spot with a clear walking route.')}
        else{this.player.yaw=Math.atan2(this.player.x-next.x,this.player.z-next.z);forward=1;if(Math.hypot(this.player.x-this.clickLast.x,this.player.z-this.clickLast.z)>.2){this.clickLast.set(this.player.x,this.player.y,this.player.z);this.clickProgressAt=this.skyTime}else if(this.skyTime-this.clickProgressAt>3){this.cancelClickTravel();forward=0;this.callbacks.message('The route is blocked. Choose another spot or steer around the obstacle.')}}}
    }
    const running=this.keys.has(this.binding('run'))||this.padMove.run,speed=swimming?2.6:this.world.life?.riding?(running?12:6):running?7:3.6,norm=Math.hypot(forward,side)||1
    const dx=(-Math.sin(this.player.yaw)*forward+Math.cos(this.player.yaw)*side)/norm*speed*dt,dz=(-Math.cos(this.player.yaw)*forward-Math.sin(this.player.yaw)*side)/norm*speed*dt,steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/0.12))
    for(let i=0;i<steps;i++){for(const axis of ['x','z'] as const){const amount=(axis==='x'?dx:dz)/steps;if(!amount)continue;const p={...this.player,[axis]:this.player[axis]+amount};if(combatBlocks(this.world,p,this.player))continue;if(clear(p,this.world))this.player[axis]=p[axis];else if(this.velocityY<=0&&clear({...p,y:p.y+0.35},this.world)){this.player[axis]=p[axis];this.player.y+=0.35}}}
    const grounded=!clear({...this.player,y:this.player.y-0.13},this.world)
    if(swimming)this.velocityY=this.keys.has(this.binding('dive'))?-2.4:(this.keys.has(this.binding('jump'))||this.padMove.jump)?3:Math.max(-2,Math.min(2,(water-1.15-this.player.y)*4))
    else{if(grounded&&(this.keys.has(this.binding('jump'))||this.padMove.jump)){this.velocityY=5.2;this.keys.delete(this.binding('jump'))}this.velocityY=Math.max(-12,this.velocityY-15*dt)}
    const vertical=this.velocityY*dt,vsteps=Math.max(1,Math.ceil(Math.abs(vertical)/0.035));for(let i=0;i<vsteps;i++){const next={...this.player,y:this.player.y+vertical/vsteps};if(clear(next,this.world))this.player.y=next.y;else{this.velocityY=0;break}}
    if(this.player.y<fallFloor(this.world)){this.player={...this.world.player};this.velocityY=0;this.callbacks.message('Returned to your last safe saved position.')}
  }
  private loop=()=>{if(this.disposed)return;const now=performance.now(),rawDt=(now-this.lastFrame)/1000;this.lastFrame=now;const dt=Math.min(0.05,rawDt),simDt=this.world.life?.paused?0:dt;this.skyTime+=simDt;this.gamepad(dt);if(this.qaUntil&&this.skyTime>=this.qaUntil){this.qaUntil=0;this.keys.clear()}this.move(simDt);this.workbench.update(simDt,this.world,this.player);this.combat.update(simDt,this.world,this.player,this.availableAssets);this.lifeView.update(this.world,this.player,simDt,this.availableAssets);this.audio.update(this.world,this.player,simDt);this.atmosphere();this.updateAvatar(simDt);this.camera.position.set(this.player.x,this.player.y+PLAYER_HEIGHT-0.08+(this.world.life?.riding?.7:0),this.player.z);this.camera.rotation.order='YXZ';this.camera.rotation.set(this.player.pitch,this.player.yaw,0);if(isAtlas(this.world)){if(!this.world.life?.interior)this.atlas?.update(this.player);if(this.overview&&!this.world.life?.interior){const town=nearestDestination(this.player.x,this.player.z);this.camera.position.set(town.x+90,height(town.x,town.z,this.world)+65,town.z+100);this.camera.rotation.set(-Math.atan2(61,Math.hypot(90,125)),Math.atan2(90,125),0);if(this.landmarkView){const p=townPlots(town).find(p=>p.label)||townPlots(town)[0];if(p){const c=Math.cos(p.yaw),sn=Math.sin(p.yaw),dx=13*c+29*sn,dz=-13*sn+29*c,zoom=Math.max(1,p.scale);this.camera.position.set(p.x+dx*zoom,height(p.x,p.z,this.world)+10*zoom,p.z+dz*zoom);this.camera.rotation.set(-Math.atan2(7,Math.hypot(dx,dz)),Math.atan2(dx,dz),0)}}}const sunAngle=hourAt(this.world.time)/24*Math.PI*2-Math.PI/2;this.sun.position.set(this.player.x+Math.cos(sunAngle)*100,this.player.y+Math.max(10,Math.sin(sunAngle)*130),this.player.z+45);this.sun.target.position.set(this.player.x,this.player.y,this.player.z);this.sun.target.updateMatrixWorld();this.scene.position.set(-Math.round(this.player.x/256)*256,0,-Math.round(this.player.z/256)*256);this.atlasOrigin.value.set(-this.scene.position.x,-this.scene.position.z);this.farCenter.value.set(this.player.x,this.player.z)}if(this.world.life?.settings.camera==='third'&&!this.overview){const offset=new T.Vector3(0,this.world.life?.riding?2.3:1.4,this.world.life?.riding?4.5:3.5).applyEuler(new T.Euler(0,this.player.yaw,0));const desired=new T.Vector3(this.player.x,this.player.y,this.player.z).add(offset);if(clear({x:desired.x,y:desired.y-.5,z:desired.z},this.world))this.camera.position.copy(desired);else if(this.avatar)this.avatar.visible=false}this.terrain();for(const chunk of this.chunks.values())chunk.mesh.visible=!this.world.life?.interior;this.atlas?.setVisible(!this.world.life?.interior);
    for(let a of this.world.animals){const obj=this.objects.get(a.id);if(!obj)continue;const health=combatActor(this.world,a.id);if(health?.vitality.hp===0){const m=this.animalMixers.get(a.id),clip=obj.children[0]?.animations.find(c=>c.name==='death');if(m&&clip){if(obj.userData.clip!=='death'){m.stopAllAction();const action=m.clipAction(clip);action.reset().setLoop(T.LoopOnce,1);action.clampWhenFinished=true;action.play();obj.userData.clip='death'}m.timeScale=1;m.update(simDt)}else obj.rotation.z=T.MathUtils.damp(obj.rotation.z,Math.PI*.45,5,simDt);obj.userData.label=`${a.name} · defeated`;continue}obj.rotation.z=0;const base=(obj.userData.groundPosition||=obj.position.clone()) as T.Vector3;const ridden=this.world.life?.riding===a.id;if(ridden){a={...a,position:{x:this.player.x,y:surfaceAt(this.player.x,this.player.z,this.world,this.player.y+1),z:this.player.z}}}const dx=a.position.x-base.x,dz=a.position.z-base.z;const moving=Math.hypot(dx,dz)>0.02||(a.species==='bird'&&Math.abs(a.position.y-base.y)>0.02);if(ridden)base.set(a.position.x,a.position.y,a.position.z);else base.lerp(new T.Vector3(a.position.x,a.position.y,a.position.z),1-Math.exp(-dt*3));obj.position.copy(base);if(ridden)obj.rotation.y=this.player.yaw+Math.PI;else if(Math.hypot(dx,dz)>0.01)obj.rotation.y=Math.atan2(dx,dz);const phase=this.skyTime*(a.activity==='fleeing'?11:6)+a.tint*8;
      if(!this.animalModels.has(a.id)){
        if((a.species==='rabbit'||a.species==='frog')&&moving)obj.position.y+=Math.max(0,Math.sin(phase))*(a.species==='frog'?0.12:0.1)
        obj.rotation.x=['pecking','rooting','grazing'].includes(a.activity||'')?Math.max(0,Math.sin(phase*0.5))*0.1:0
        const limbs=obj.userData.legs as T.Object3D[]|undefined;limbs?.forEach((limb,i)=>{const flying=a.species==='bird'&&a.activity!=='perching',swimming=a.species==='fish';limb.rotation.x=(moving||flying||swimming?1:0)*Math.sin(this.skyTime*(flying?12:swimming?7:6)+i*Math.PI)*(flying?0.8:0.25)})
      }
      const mixer=this.animalMixers.get(a.id);if(mixer){const source=obj.children[0],desired=a.species==='fish'?'swim':a.species==='bird'?(a.activity==='perching'?'perch':'fly'):moving?(a.activity==='fleeing'||ridden&&this.keys.has(this.binding('run'))?'run':'walk'):['grazing','pecking','rooting','feeding'].includes(a.activity||'')?'eat':a.activity==='resting'?'rest':'idle',clip=source.animations.find(c=>c.name===desired)||source.animations[0];if(clip&&obj.userData.clip!==clip.name){mixer.stopAllAction();mixer.clipAction(clip).reset().play();obj.userData.clip=clip.name}mixer.timeScale=1;mixer.update(simDt)}}
    for(const resident of this.residents.values()){resident.root.visible=!this.world.life?.interior&&!this.world.life?.residents.find(r=>r.id===resident.root.userData.id)?.insideBuilding;const a=combatActor(this.world,resident.root.userData.id);if(!a)continue;resident.root.position.lerp(new T.Vector3(a.position.x,a.position.y,a.position.z),1-Math.exp(-dt*10));resident.root.rotation.y=a.yaw;resident.root.userData.label=`${a.name} · ${Math.ceil(a.vitality.hp)}/${a.vitality.maxHp}`;if(!living(a)){const clip=resident.root.children[0]?.animations.find(c=>c.name==='death');if(clip){if(resident.root.userData.clip!=='death'){resident.mixer.stopAllAction();const action=resident.mixer.clipAction(clip);action.reset().setLoop(T.LoopOnce,1);action.clampWhenFinished=true;action.play();resident.root.userData.clip='death'}resident.mixer.update(simDt)}else resident.root.rotation.z=T.MathUtils.damp(resident.root.rotation.z,Math.PI*.45,5,simDt)}else{resident.root.rotation.z=0;const source=resident.root.children[0],npc=this.world.life?.residents.find(r=>r.id===a.id),name=a.phase==='windup'||a.phase==='recover'?'hit':npc?.activity==='sleeping'?'rest':npc?.activity==='walking'?'walk':'idle',clip=source.animations.find(c=>c.name.toLowerCase()===name)||source.animations[0];if(clip&&resident.root.userData.clip!==clip.name){resident.mixer.stopAllAction();resident.mixer.clipAction(clip).reset().play();resident.root.userData.clip=clip.name}resident.mixer.timeScale=1;resident.mixer.update(simDt)}}
    this.renderer.render(this.scene,this.camera);this.frameTimes.push(rawDt);if(this.frameTimes.length>120)this.frameTimes.shift();this.viewTimer+=dt;if(this.viewTimer>0.15){this.viewTimer=0;if(new URLSearchParams(location.search).has('combatQA'))this.renderer.domElement.dataset.combatQa=JSON.stringify({worldId:this.world.id,time:this.world.time,input:{mouseForward:this.mouseTravel.forward,clickDestination:this.clickDestination},player:{...this.player,vitality:combatActor(this.world,'player')?.vitality},actors:this.world.combat?.actors.filter(a=>Math.hypot(a.position.x-this.player.x,a.position.z-this.player.z)<200),view:this.combat.diagnostics,performance:this.getPerformanceDiagnostics(),drawCalls:this.renderer.info.render.calls});const label=this.updateTarget();this.callbacks.view({x:this.player.x,y:this.player.y,z:this.player.z,fps:Math.round(this.frameTimes.length/this.frameTimes.reduce((a,b)=>a+b,0)),pending:this.queue.length+this.inflight.size,target:label,targetId:this.targetId,targetKind:this.target,yaw:this.player.yaw,caption:this.skyTime<this.captionUntil?this.caption:undefined,region:this.world.life?.interior?.label||(isAtlas(this.world)?regionAt(this.player.x,this.player.z):this.cinderlord&&Math.hypot(this.player.x-this.cinderlord.site.x,this.player.z-this.cinderlord.site.z)<90?'Ashen Hollow':this.player.x>1050&&this.player.z>1050?'Fangorn Forest':'The Shire'),enemy:this.cinderlord&&Math.hypot(this.player.x-this.cinderlord.site.x,this.player.z-this.cinderlord.site.z)<60?this.cinderlord.status:undefined,locked:document.pointerLockElement===this.renderer.domElement,preview:this.previewLabel});this.loadResidents();this.cinderlord?.load(this.availableAssets.get(CINDERLORD.assetId),this.player)}
    this.loopHandle=requestAnimationFrame(this.loop)
  }
  private atmosphere(){const l=this.world.life;if(!l)return;const hour=hourAt(this.world.time),day=T.MathUtils.smoothstep(Math.sin((hour-6)/24*Math.PI*2),-.12,.32),cloud=l.weather.kind==='rain'?.5:l.weather.kind==='cloudy'?.75:1;this.hemisphere.intensity=.48+day*1.2*cloud;this.sun.intensity=.16+day*1.94*cloud;const sky=new T.Color(0x294258).lerp(new T.Color(0xb8c9bd),day);if(l.weather.kind==='rain')sky.lerp(new T.Color(0x6e827e),.4);this.scene.background=sky;const fog=this.scene.fog as T.FogExp2;if(fog){fog.color.copy(sky);fog.density=l.interior?.018:l.weather.kind==='mist'?.006:l.weather.kind==='rain'?.0018:.0007}this.renderer.toneMappingExposure=l.interior?1.05:.9}
  private updateAvatar(dt:number){const l=this.world.life;if(!l)return;const key=l.avatar.kind==='human'?'resident-human':l.avatar.female?'resident-hobbit-female':'resident-hobbit-male';if(this.avatarKey!==key&&this.avatarLoading!==key){const url=this.availableAssets.get(key);if(url){this.avatarLoading=key;void LoadManager.glTFLoad(url).then(model=>{if(this.disposed){LoadManager.releaseClone(model);return}if(this.avatar){this.scene.remove(this.avatar);LoadManager.releaseClone(this.avatar)}if(key==='resident-human'){const bounds=new T.Box3().setFromObject(model);const scale=1.7/Math.max(.01,bounds.max.y-bounds.min.y);model.scale.multiplyScalar(scale);model.userData.feetOffset=-bounds.min.y*scale}this.avatar=model;this.riderPose=new RiderPose(model);this.avatarKey=key;this.avatarMixer=new T.AnimationMixer(model);this.scene.add(model)}).finally(()=>this.avatarLoading='')}}if(!this.avatar)return;this.avatar.visible=l.settings.camera==='third'&&!this.overview;this.avatar.position.set(this.player.x,this.player.y+.12+(l.riding?.68:0)+(this.avatar.userData.feetOffset||0),this.player.z);this.avatar.rotation.y=this.player.yaw+Math.PI;const moving=[this.binding('forward'),this.binding('back'),this.binding('left'),this.binding('right')].some(k=>this.keys.has(k))||Math.hypot(this.padMove.forward,this.padMove.side)>.1||this.mouseTravel.forward||!!this.clickDestination,name=l.riding?'idle':moving?'walk':l.seated?'rest':'idle',clip=this.avatar.animations.find(c=>c.name===name)||this.avatar.animations[0];if(clip&&this.avatar.userData.clip!==clip.name){this.avatarMixer!.stopAllAction();this.avatarMixer!.clipAction(clip).reset().play();this.avatar.userData.clip=clip.name}this.avatarMixer?.update(dt);if(l.riding)this.riderPose?.apply();this.avatar.traverse(o=>{if(o instanceof T.Mesh)for(const material of Array.isArray(o.material)?o.material:[o.material])if(material instanceof T.MeshStandardMaterial&&['Waistcoat','Blue'].includes(material.name))material.color.setHex(l.avatar.colour)})}
  dispose(){if(this.disposed)return;this.disposed=true;this.releaseInput();this.workbench.dispose();this.lifeView.dispose();this.audio.dispose();if(this.avatar){this.scene.remove(this.avatar);LoadManager.releaseClone(this.avatar)}this.combat.dispose();this.cinderlord?.dispose();this.atlas?.dispose();cancelAnimationFrame(this.loopHandle);this.resizeObserver.disconnect();for(const worker of this.workers)worker.terminate();window.removeEventListener('keydown',this.keyDown);window.removeEventListener('keyup',this.keyUp);window.removeEventListener('blur',this.releaseInput);document.removeEventListener('pointerlockchange',this.lockChange);document.removeEventListener('mousemove',this.mouseMove);document.removeEventListener('mouseup',this.mouseUp);this.renderer.domElement.removeEventListener('mousedown',this.mouseDown);this.renderer.domElement.removeEventListener('contextmenu',this.contextMenu);this.renderer.domElement.removeEventListener('pointerdown',this.touchDown);this.renderer.domElement.removeEventListener('pointermove',this.touchMove);this.renderer.domElement.removeEventListener('pointerup',this.touchUp);this.renderer.domElement.removeEventListener('pointercancel',this.touchUp);for(const key of [...this.objects.keys()])this.removeObject(key);for(const r of this.residents.values()){r.mixer.stopAllAction();LoadManager.releaseClone(r.root);this.scene.remove(r.root)}disposeObject(this.scene);this.terrainMaterial.dispose();this.renderer.dispose();this.renderer.domElement.remove()}
}
